/*
 * Goodsender API
 *
 * Goodsender API. ### Authorization  All API requests require an API key in the `Authorization` header:  ``` Authorization: Bearer <your-api-key> ``` 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@goodsender.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using GoodSender.Client;
using GoodSender.Model;

namespace GoodSender.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IDomainsApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// List domains
        /// </summary>
        /// <remarks>
        /// Retrieve a paginated list of sender domains for the workspace the API key belongs to. Each entry includes the domain&#39;s verification state so callers can detect when DNS records still need attention. 
        /// </remarks>
        /// <exception cref="GoodSender.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="limit">Maximum number of records to return. (optional, default to 50)</param>
        /// <param name="cursor">Cursor for pagination, returned as &#x60;nextCursor&#x60; from a previous response. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>DomainListResponse</returns>
        DomainListResponse ListDomains(int? limit = default, string? cursor = default, int operationIndex = 0);

        /// <summary>
        /// List domains
        /// </summary>
        /// <remarks>
        /// Retrieve a paginated list of sender domains for the workspace the API key belongs to. Each entry includes the domain&#39;s verification state so callers can detect when DNS records still need attention. 
        /// </remarks>
        /// <exception cref="GoodSender.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="limit">Maximum number of records to return. (optional, default to 50)</param>
        /// <param name="cursor">Cursor for pagination, returned as &#x60;nextCursor&#x60; from a previous response. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of DomainListResponse</returns>
        ApiResponse<DomainListResponse> ListDomainsWithHttpInfo(int? limit = default, string? cursor = default, int operationIndex = 0);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IDomainsApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// List domains
        /// </summary>
        /// <remarks>
        /// Retrieve a paginated list of sender domains for the workspace the API key belongs to. Each entry includes the domain&#39;s verification state so callers can detect when DNS records still need attention. 
        /// </remarks>
        /// <exception cref="GoodSender.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="limit">Maximum number of records to return. (optional, default to 50)</param>
        /// <param name="cursor">Cursor for pagination, returned as &#x60;nextCursor&#x60; from a previous response. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of DomainListResponse</returns>
        System.Threading.Tasks.Task<DomainListResponse> ListDomainsAsync(int? limit = default, string? cursor = default, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// List domains
        /// </summary>
        /// <remarks>
        /// Retrieve a paginated list of sender domains for the workspace the API key belongs to. Each entry includes the domain&#39;s verification state so callers can detect when DNS records still need attention. 
        /// </remarks>
        /// <exception cref="GoodSender.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="limit">Maximum number of records to return. (optional, default to 50)</param>
        /// <param name="cursor">Cursor for pagination, returned as &#x60;nextCursor&#x60; from a previous response. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (DomainListResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<DomainListResponse>> ListDomainsWithHttpInfoAsync(int? limit = default, string? cursor = default, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IDomainsApi : IDomainsApiSync, IDomainsApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class DomainsApi : IDomainsApi
    {
        private GoodSender.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="DomainsApi"/> class.
        /// </summary>
        /// <returns></returns>
        public DomainsApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DomainsApi"/> class.
        /// </summary>
        /// <returns></returns>
        public DomainsApi(string basePath)
        {
            this.Configuration = GoodSender.Client.Configuration.MergeConfigurations(
                GoodSender.Client.GlobalConfiguration.Instance,
                new GoodSender.Client.Configuration { BasePath = basePath }
            );
            this.Client = new GoodSender.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new GoodSender.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = GoodSender.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DomainsApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public DomainsApi(GoodSender.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = GoodSender.Client.Configuration.MergeConfigurations(
                GoodSender.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new GoodSender.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new GoodSender.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = GoodSender.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DomainsApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public DomainsApi(GoodSender.Client.ISynchronousClient client, GoodSender.Client.IAsynchronousClient asyncClient, GoodSender.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = GoodSender.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public GoodSender.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public GoodSender.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public GoodSender.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public GoodSender.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// List domains Retrieve a paginated list of sender domains for the workspace the API key belongs to. Each entry includes the domain&#39;s verification state so callers can detect when DNS records still need attention. 
        /// </summary>
        /// <exception cref="GoodSender.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="limit">Maximum number of records to return. (optional, default to 50)</param>
        /// <param name="cursor">Cursor for pagination, returned as &#x60;nextCursor&#x60; from a previous response. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>DomainListResponse</returns>
        public DomainListResponse ListDomains(int? limit = default, string? cursor = default, int operationIndex = 0)
        {
            GoodSender.Client.ApiResponse<DomainListResponse> localVarResponse = ListDomainsWithHttpInfo(limit, cursor);
            return localVarResponse.Data;
        }

        /// <summary>
        /// List domains Retrieve a paginated list of sender domains for the workspace the API key belongs to. Each entry includes the domain&#39;s verification state so callers can detect when DNS records still need attention. 
        /// </summary>
        /// <exception cref="GoodSender.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="limit">Maximum number of records to return. (optional, default to 50)</param>
        /// <param name="cursor">Cursor for pagination, returned as &#x60;nextCursor&#x60; from a previous response. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of DomainListResponse</returns>
        public GoodSender.Client.ApiResponse<DomainListResponse> ListDomainsWithHttpInfo(int? limit = default, string? cursor = default, int operationIndex = 0)
        {
            GoodSender.Client.RequestOptions localVarRequestOptions = new GoodSender.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = GoodSender.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            var localVarMultipartFormData = localVarContentType == "multipart/form-data";
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = GoodSender.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            if (limit != null)
            {
                localVarRequestOptions.QueryParameters.Add(GoodSender.Client.ClientUtils.ParameterToMultiMap("", "limit", limit));
            }
            if (cursor != null)
            {
                localVarRequestOptions.QueryParameters.Add(GoodSender.Client.ClientUtils.ParameterToMultiMap("", "cursor", cursor));
            }

            localVarRequestOptions.Operation = "DomainsApi.ListDomains";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (bearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<DomainListResponse>("/v1/domains", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ListDomains", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// List domains Retrieve a paginated list of sender domains for the workspace the API key belongs to. Each entry includes the domain&#39;s verification state so callers can detect when DNS records still need attention. 
        /// </summary>
        /// <exception cref="GoodSender.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="limit">Maximum number of records to return. (optional, default to 50)</param>
        /// <param name="cursor">Cursor for pagination, returned as &#x60;nextCursor&#x60; from a previous response. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of DomainListResponse</returns>
        public async System.Threading.Tasks.Task<DomainListResponse> ListDomainsAsync(int? limit = default, string? cursor = default, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default)
        {
            GoodSender.Client.ApiResponse<DomainListResponse> localVarResponse = await ListDomainsWithHttpInfoAsync(limit, cursor, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// List domains Retrieve a paginated list of sender domains for the workspace the API key belongs to. Each entry includes the domain&#39;s verification state so callers can detect when DNS records still need attention. 
        /// </summary>
        /// <exception cref="GoodSender.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="limit">Maximum number of records to return. (optional, default to 50)</param>
        /// <param name="cursor">Cursor for pagination, returned as &#x60;nextCursor&#x60; from a previous response. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (DomainListResponse)</returns>
        public async System.Threading.Tasks.Task<GoodSender.Client.ApiResponse<DomainListResponse>> ListDomainsWithHttpInfoAsync(int? limit = default, string? cursor = default, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default)
        {

            GoodSender.Client.RequestOptions localVarRequestOptions = new GoodSender.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = GoodSender.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = GoodSender.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            if (limit != null)
            {
                localVarRequestOptions.QueryParameters.Add(GoodSender.Client.ClientUtils.ParameterToMultiMap("", "limit", limit));
            }
            if (cursor != null)
            {
                localVarRequestOptions.QueryParameters.Add(GoodSender.Client.ClientUtils.ParameterToMultiMap("", "cursor", cursor));
            }

            localVarRequestOptions.Operation = "DomainsApi.ListDomains";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (bearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<DomainListResponse>("/v1/domains", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ListDomains", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

    }
}
