/*
 * Goodsender API
 *
 * Goodsender API. ### Authorization  All API requests require an API key in the `Authorization` header:  ``` Authorization: Bearer <your-api-key> ``` 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@goodsender.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using GoodSender.Client;
using GoodSender.Model;

namespace GoodSender.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IEmailsApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Get recipient consent status
        /// </summary>
        /// <remarks>
        /// Retrieve the current consent status for an email address. Optionally filter by sender domain.
        /// </remarks>
        /// <exception cref="GoodSender.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="email">Email address to look up.</param>
        /// <param name="domain">Optional sender domain to filter consent records by. When omitted, returns consent across all domains. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>List&lt;EmailAccount&gt;</returns>
        List<EmailAccount> GetEmailConsentStatus(string email, string? domain = default, int operationIndex = 0);

        /// <summary>
        /// Get recipient consent status
        /// </summary>
        /// <remarks>
        /// Retrieve the current consent status for an email address. Optionally filter by sender domain.
        /// </remarks>
        /// <exception cref="GoodSender.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="email">Email address to look up.</param>
        /// <param name="domain">Optional sender domain to filter consent records by. When omitted, returns consent across all domains. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of List&lt;EmailAccount&gt;</returns>
        ApiResponse<List<EmailAccount>> GetEmailConsentStatusWithHttpInfo(string email, string? domain = default, int operationIndex = 0);
        /// <summary>
        /// List email consent statuses
        /// </summary>
        /// <remarks>
        /// Retrieve a paginated list of email consent statuses for a domain.
        /// </remarks>
        /// <exception cref="GoodSender.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="domain">Sender domain to filter consent records by.</param>
        /// <param name="limit">Maximum number of records to return. (optional, default to 50)</param>
        /// <param name="cursor">Cursor for pagination. (optional)</param>
        /// <param name="consentStatus">Status of the recipient&#39;s consent for receiving emails. &#39;pending&#39; &#x3D; awaiting consent email send, &#39;requested&#39; &#x3D; consent email dispatched, &#39;failed&#39; &#x3D; consent email delivery failed, &#39;granted&#39; &#x3D; recipient consented to receive emails, &#39;denied&#39; &#x3D; recipient declined to receive emails. (optional)</param>
        /// <param name="engagementStatus">Status of the recipient&#39;s engagement with the emails. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>EmailListResponse</returns>
        EmailListResponse ListEmailConsents(string domain, int? limit = default, string? cursor = default, string? consentStatus = default, string? engagementStatus = default, int operationIndex = 0);

        /// <summary>
        /// List email consent statuses
        /// </summary>
        /// <remarks>
        /// Retrieve a paginated list of email consent statuses for a domain.
        /// </remarks>
        /// <exception cref="GoodSender.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="domain">Sender domain to filter consent records by.</param>
        /// <param name="limit">Maximum number of records to return. (optional, default to 50)</param>
        /// <param name="cursor">Cursor for pagination. (optional)</param>
        /// <param name="consentStatus">Status of the recipient&#39;s consent for receiving emails. &#39;pending&#39; &#x3D; awaiting consent email send, &#39;requested&#39; &#x3D; consent email dispatched, &#39;failed&#39; &#x3D; consent email delivery failed, &#39;granted&#39; &#x3D; recipient consented to receive emails, &#39;denied&#39; &#x3D; recipient declined to receive emails. (optional)</param>
        /// <param name="engagementStatus">Status of the recipient&#39;s engagement with the emails. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of EmailListResponse</returns>
        ApiResponse<EmailListResponse> ListEmailConsentsWithHttpInfo(string domain, int? limit = default, string? cursor = default, string? consentStatus = default, string? engagementStatus = default, int operationIndex = 0);
        /// <summary>
        /// Request recipients&#39; consent to receive emails from your domain
        /// </summary>
        /// <remarks>
        /// Send a consent message to each address so recipients can approve or reject future emails from your domain. Include the email addresses in the request body to start the consent flow. 
        /// </remarks>
        /// <exception cref="GoodSender.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="consentEmailRequest"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ConsentEmailResult</returns>
        ConsentEmailResult RequestEmailConsent(ConsentEmailRequest consentEmailRequest, int operationIndex = 0);

        /// <summary>
        /// Request recipients&#39; consent to receive emails from your domain
        /// </summary>
        /// <remarks>
        /// Send a consent message to each address so recipients can approve or reject future emails from your domain. Include the email addresses in the request body to start the consent flow. 
        /// </remarks>
        /// <exception cref="GoodSender.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="consentEmailRequest"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of ConsentEmailResult</returns>
        ApiResponse<ConsentEmailResult> RequestEmailConsentWithHttpInfo(ConsentEmailRequest consentEmailRequest, int operationIndex = 0);
        /// <summary>
        /// Send an email or a batch of emails
        /// </summary>
        /// <remarks>
        /// Send one or more emails. Emails can be sent only to recipients who have opted in to receive communications from your domain. The response indicates how many emails were sent versus not sent, based on each recipient&#39;s consent state. 
        /// </remarks>
        /// <exception cref="GoodSender.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="sendEmailRequest">List of emails to send</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>SendEmailResponse</returns>
        SendEmailResponse SendEmail(SendEmailRequest sendEmailRequest, int operationIndex = 0);

        /// <summary>
        /// Send an email or a batch of emails
        /// </summary>
        /// <remarks>
        /// Send one or more emails. Emails can be sent only to recipients who have opted in to receive communications from your domain. The response indicates how many emails were sent versus not sent, based on each recipient&#39;s consent state. 
        /// </remarks>
        /// <exception cref="GoodSender.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="sendEmailRequest">List of emails to send</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of SendEmailResponse</returns>
        ApiResponse<SendEmailResponse> SendEmailWithHttpInfo(SendEmailRequest sendEmailRequest, int operationIndex = 0);
        /// <summary>
        /// Send a transactional email using a template
        /// </summary>
        /// <remarks>
        /// Send a transactional email using a predefined template for common use cases like OTP codes, order confirmations, and new device login alerts. If the recipient has \&quot;denied\&quot; consent, the response returns &#x60;{\&quot;status\&quot;: \&quot;declined\&quot;}&#x60; and the email is not sent. Unknown recipients are auto-registered with \&quot;pending\&quot; consent. The template endpoint does not change the recipient&#39;s consent. Each email includes an approve/reject footer allowing the recipient to manage future communications. Provide the template ID and any variables to fill in the placeholders. All variables are optional and will be replaced with an empty string if omitted. URL-type variables must point to the same domain as the sender&#39;s email address. 
        /// </remarks>
        /// <exception cref="GoodSender.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="templateEmailRequest">Template email to send</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>TemplateEmailResponse</returns>
        TemplateEmailResponse SendTemplateEmail(TemplateEmailRequest templateEmailRequest, int operationIndex = 0);

        /// <summary>
        /// Send a transactional email using a template
        /// </summary>
        /// <remarks>
        /// Send a transactional email using a predefined template for common use cases like OTP codes, order confirmations, and new device login alerts. If the recipient has \&quot;denied\&quot; consent, the response returns &#x60;{\&quot;status\&quot;: \&quot;declined\&quot;}&#x60; and the email is not sent. Unknown recipients are auto-registered with \&quot;pending\&quot; consent. The template endpoint does not change the recipient&#39;s consent. Each email includes an approve/reject footer allowing the recipient to manage future communications. Provide the template ID and any variables to fill in the placeholders. All variables are optional and will be replaced with an empty string if omitted. URL-type variables must point to the same domain as the sender&#39;s email address. 
        /// </remarks>
        /// <exception cref="GoodSender.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="templateEmailRequest">Template email to send</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of TemplateEmailResponse</returns>
        ApiResponse<TemplateEmailResponse> SendTemplateEmailWithHttpInfo(TemplateEmailRequest templateEmailRequest, int operationIndex = 0);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IEmailsApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Get recipient consent status
        /// </summary>
        /// <remarks>
        /// Retrieve the current consent status for an email address. Optionally filter by sender domain.
        /// </remarks>
        /// <exception cref="GoodSender.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="email">Email address to look up.</param>
        /// <param name="domain">Optional sender domain to filter consent records by. When omitted, returns consent across all domains. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;EmailAccount&gt;</returns>
        System.Threading.Tasks.Task<List<EmailAccount>> GetEmailConsentStatusAsync(string email, string? domain = default, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Get recipient consent status
        /// </summary>
        /// <remarks>
        /// Retrieve the current consent status for an email address. Optionally filter by sender domain.
        /// </remarks>
        /// <exception cref="GoodSender.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="email">Email address to look up.</param>
        /// <param name="domain">Optional sender domain to filter consent records by. When omitted, returns consent across all domains. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;EmailAccount&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<EmailAccount>>> GetEmailConsentStatusWithHttpInfoAsync(string email, string? domain = default, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// List email consent statuses
        /// </summary>
        /// <remarks>
        /// Retrieve a paginated list of email consent statuses for a domain.
        /// </remarks>
        /// <exception cref="GoodSender.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="domain">Sender domain to filter consent records by.</param>
        /// <param name="limit">Maximum number of records to return. (optional, default to 50)</param>
        /// <param name="cursor">Cursor for pagination. (optional)</param>
        /// <param name="consentStatus">Status of the recipient&#39;s consent for receiving emails. &#39;pending&#39; &#x3D; awaiting consent email send, &#39;requested&#39; &#x3D; consent email dispatched, &#39;failed&#39; &#x3D; consent email delivery failed, &#39;granted&#39; &#x3D; recipient consented to receive emails, &#39;denied&#39; &#x3D; recipient declined to receive emails. (optional)</param>
        /// <param name="engagementStatus">Status of the recipient&#39;s engagement with the emails. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of EmailListResponse</returns>
        System.Threading.Tasks.Task<EmailListResponse> ListEmailConsentsAsync(string domain, int? limit = default, string? cursor = default, string? consentStatus = default, string? engagementStatus = default, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// List email consent statuses
        /// </summary>
        /// <remarks>
        /// Retrieve a paginated list of email consent statuses for a domain.
        /// </remarks>
        /// <exception cref="GoodSender.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="domain">Sender domain to filter consent records by.</param>
        /// <param name="limit">Maximum number of records to return. (optional, default to 50)</param>
        /// <param name="cursor">Cursor for pagination. (optional)</param>
        /// <param name="consentStatus">Status of the recipient&#39;s consent for receiving emails. &#39;pending&#39; &#x3D; awaiting consent email send, &#39;requested&#39; &#x3D; consent email dispatched, &#39;failed&#39; &#x3D; consent email delivery failed, &#39;granted&#39; &#x3D; recipient consented to receive emails, &#39;denied&#39; &#x3D; recipient declined to receive emails. (optional)</param>
        /// <param name="engagementStatus">Status of the recipient&#39;s engagement with the emails. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (EmailListResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<EmailListResponse>> ListEmailConsentsWithHttpInfoAsync(string domain, int? limit = default, string? cursor = default, string? consentStatus = default, string? engagementStatus = default, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// Request recipients&#39; consent to receive emails from your domain
        /// </summary>
        /// <remarks>
        /// Send a consent message to each address so recipients can approve or reject future emails from your domain. Include the email addresses in the request body to start the consent flow. 
        /// </remarks>
        /// <exception cref="GoodSender.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="consentEmailRequest"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ConsentEmailResult</returns>
        System.Threading.Tasks.Task<ConsentEmailResult> RequestEmailConsentAsync(ConsentEmailRequest consentEmailRequest, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Request recipients&#39; consent to receive emails from your domain
        /// </summary>
        /// <remarks>
        /// Send a consent message to each address so recipients can approve or reject future emails from your domain. Include the email addresses in the request body to start the consent flow. 
        /// </remarks>
        /// <exception cref="GoodSender.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="consentEmailRequest"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ConsentEmailResult)</returns>
        System.Threading.Tasks.Task<ApiResponse<ConsentEmailResult>> RequestEmailConsentWithHttpInfoAsync(ConsentEmailRequest consentEmailRequest, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// Send an email or a batch of emails
        /// </summary>
        /// <remarks>
        /// Send one or more emails. Emails can be sent only to recipients who have opted in to receive communications from your domain. The response indicates how many emails were sent versus not sent, based on each recipient&#39;s consent state. 
        /// </remarks>
        /// <exception cref="GoodSender.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="sendEmailRequest">List of emails to send</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of SendEmailResponse</returns>
        System.Threading.Tasks.Task<SendEmailResponse> SendEmailAsync(SendEmailRequest sendEmailRequest, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Send an email or a batch of emails
        /// </summary>
        /// <remarks>
        /// Send one or more emails. Emails can be sent only to recipients who have opted in to receive communications from your domain. The response indicates how many emails were sent versus not sent, based on each recipient&#39;s consent state. 
        /// </remarks>
        /// <exception cref="GoodSender.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="sendEmailRequest">List of emails to send</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (SendEmailResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<SendEmailResponse>> SendEmailWithHttpInfoAsync(SendEmailRequest sendEmailRequest, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// Send a transactional email using a template
        /// </summary>
        /// <remarks>
        /// Send a transactional email using a predefined template for common use cases like OTP codes, order confirmations, and new device login alerts. If the recipient has \&quot;denied\&quot; consent, the response returns &#x60;{\&quot;status\&quot;: \&quot;declined\&quot;}&#x60; and the email is not sent. Unknown recipients are auto-registered with \&quot;pending\&quot; consent. The template endpoint does not change the recipient&#39;s consent. Each email includes an approve/reject footer allowing the recipient to manage future communications. Provide the template ID and any variables to fill in the placeholders. All variables are optional and will be replaced with an empty string if omitted. URL-type variables must point to the same domain as the sender&#39;s email address. 
        /// </remarks>
        /// <exception cref="GoodSender.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="templateEmailRequest">Template email to send</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of TemplateEmailResponse</returns>
        System.Threading.Tasks.Task<TemplateEmailResponse> SendTemplateEmailAsync(TemplateEmailRequest templateEmailRequest, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Send a transactional email using a template
        /// </summary>
        /// <remarks>
        /// Send a transactional email using a predefined template for common use cases like OTP codes, order confirmations, and new device login alerts. If the recipient has \&quot;denied\&quot; consent, the response returns &#x60;{\&quot;status\&quot;: \&quot;declined\&quot;}&#x60; and the email is not sent. Unknown recipients are auto-registered with \&quot;pending\&quot; consent. The template endpoint does not change the recipient&#39;s consent. Each email includes an approve/reject footer allowing the recipient to manage future communications. Provide the template ID and any variables to fill in the placeholders. All variables are optional and will be replaced with an empty string if omitted. URL-type variables must point to the same domain as the sender&#39;s email address. 
        /// </remarks>
        /// <exception cref="GoodSender.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="templateEmailRequest">Template email to send</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (TemplateEmailResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<TemplateEmailResponse>> SendTemplateEmailWithHttpInfoAsync(TemplateEmailRequest templateEmailRequest, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IEmailsApi : IEmailsApiSync, IEmailsApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class EmailsApi : IEmailsApi
    {
        private GoodSender.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="EmailsApi"/> class.
        /// </summary>
        /// <returns></returns>
        public EmailsApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="EmailsApi"/> class.
        /// </summary>
        /// <returns></returns>
        public EmailsApi(string basePath)
        {
            this.Configuration = GoodSender.Client.Configuration.MergeConfigurations(
                GoodSender.Client.GlobalConfiguration.Instance,
                new GoodSender.Client.Configuration { BasePath = basePath }
            );
            this.Client = new GoodSender.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new GoodSender.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = GoodSender.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="EmailsApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public EmailsApi(GoodSender.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = GoodSender.Client.Configuration.MergeConfigurations(
                GoodSender.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new GoodSender.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new GoodSender.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = GoodSender.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="EmailsApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public EmailsApi(GoodSender.Client.ISynchronousClient client, GoodSender.Client.IAsynchronousClient asyncClient, GoodSender.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = GoodSender.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public GoodSender.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public GoodSender.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public GoodSender.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public GoodSender.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Get recipient consent status Retrieve the current consent status for an email address. Optionally filter by sender domain.
        /// </summary>
        /// <exception cref="GoodSender.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="email">Email address to look up.</param>
        /// <param name="domain">Optional sender domain to filter consent records by. When omitted, returns consent across all domains. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>List&lt;EmailAccount&gt;</returns>
        public List<EmailAccount> GetEmailConsentStatus(string email, string? domain = default, int operationIndex = 0)
        {
            GoodSender.Client.ApiResponse<List<EmailAccount>> localVarResponse = GetEmailConsentStatusWithHttpInfo(email, domain);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get recipient consent status Retrieve the current consent status for an email address. Optionally filter by sender domain.
        /// </summary>
        /// <exception cref="GoodSender.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="email">Email address to look up.</param>
        /// <param name="domain">Optional sender domain to filter consent records by. When omitted, returns consent across all domains. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of List&lt;EmailAccount&gt;</returns>
        public GoodSender.Client.ApiResponse<List<EmailAccount>> GetEmailConsentStatusWithHttpInfo(string email, string? domain = default, int operationIndex = 0)
        {
            // verify the required parameter 'email' is set
            if (email == null)
            {
                throw new GoodSender.Client.ApiException(400, "Missing required parameter 'email' when calling EmailsApi->GetEmailConsentStatus");
            }

            GoodSender.Client.RequestOptions localVarRequestOptions = new GoodSender.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = GoodSender.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            var localVarMultipartFormData = localVarContentType == "multipart/form-data";
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = GoodSender.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("email", GoodSender.Client.ClientUtils.ParameterToString(email)); // path parameter
            if (domain != null)
            {
                localVarRequestOptions.QueryParameters.Add(GoodSender.Client.ClientUtils.ParameterToMultiMap("", "domain", domain));
            }

            localVarRequestOptions.Operation = "EmailsApi.GetEmailConsentStatus";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (bearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<List<EmailAccount>>("/v1/emails/{email}", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetEmailConsentStatus", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get recipient consent status Retrieve the current consent status for an email address. Optionally filter by sender domain.
        /// </summary>
        /// <exception cref="GoodSender.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="email">Email address to look up.</param>
        /// <param name="domain">Optional sender domain to filter consent records by. When omitted, returns consent across all domains. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;EmailAccount&gt;</returns>
        public async System.Threading.Tasks.Task<List<EmailAccount>> GetEmailConsentStatusAsync(string email, string? domain = default, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default)
        {
            GoodSender.Client.ApiResponse<List<EmailAccount>> localVarResponse = await GetEmailConsentStatusWithHttpInfoAsync(email, domain, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get recipient consent status Retrieve the current consent status for an email address. Optionally filter by sender domain.
        /// </summary>
        /// <exception cref="GoodSender.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="email">Email address to look up.</param>
        /// <param name="domain">Optional sender domain to filter consent records by. When omitted, returns consent across all domains. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;EmailAccount&gt;)</returns>
        public async System.Threading.Tasks.Task<GoodSender.Client.ApiResponse<List<EmailAccount>>> GetEmailConsentStatusWithHttpInfoAsync(string email, string? domain = default, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default)
        {
            // verify the required parameter 'email' is set
            if (email == null)
            {
                throw new GoodSender.Client.ApiException(400, "Missing required parameter 'email' when calling EmailsApi->GetEmailConsentStatus");
            }


            GoodSender.Client.RequestOptions localVarRequestOptions = new GoodSender.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = GoodSender.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = GoodSender.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("email", GoodSender.Client.ClientUtils.ParameterToString(email)); // path parameter
            if (domain != null)
            {
                localVarRequestOptions.QueryParameters.Add(GoodSender.Client.ClientUtils.ParameterToMultiMap("", "domain", domain));
            }

            localVarRequestOptions.Operation = "EmailsApi.GetEmailConsentStatus";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (bearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<List<EmailAccount>>("/v1/emails/{email}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetEmailConsentStatus", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// List email consent statuses Retrieve a paginated list of email consent statuses for a domain.
        /// </summary>
        /// <exception cref="GoodSender.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="domain">Sender domain to filter consent records by.</param>
        /// <param name="limit">Maximum number of records to return. (optional, default to 50)</param>
        /// <param name="cursor">Cursor for pagination. (optional)</param>
        /// <param name="consentStatus">Status of the recipient&#39;s consent for receiving emails. &#39;pending&#39; &#x3D; awaiting consent email send, &#39;requested&#39; &#x3D; consent email dispatched, &#39;failed&#39; &#x3D; consent email delivery failed, &#39;granted&#39; &#x3D; recipient consented to receive emails, &#39;denied&#39; &#x3D; recipient declined to receive emails. (optional)</param>
        /// <param name="engagementStatus">Status of the recipient&#39;s engagement with the emails. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>EmailListResponse</returns>
        public EmailListResponse ListEmailConsents(string domain, int? limit = default, string? cursor = default, string? consentStatus = default, string? engagementStatus = default, int operationIndex = 0)
        {
            GoodSender.Client.ApiResponse<EmailListResponse> localVarResponse = ListEmailConsentsWithHttpInfo(domain, limit, cursor, consentStatus, engagementStatus);
            return localVarResponse.Data;
        }

        /// <summary>
        /// List email consent statuses Retrieve a paginated list of email consent statuses for a domain.
        /// </summary>
        /// <exception cref="GoodSender.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="domain">Sender domain to filter consent records by.</param>
        /// <param name="limit">Maximum number of records to return. (optional, default to 50)</param>
        /// <param name="cursor">Cursor for pagination. (optional)</param>
        /// <param name="consentStatus">Status of the recipient&#39;s consent for receiving emails. &#39;pending&#39; &#x3D; awaiting consent email send, &#39;requested&#39; &#x3D; consent email dispatched, &#39;failed&#39; &#x3D; consent email delivery failed, &#39;granted&#39; &#x3D; recipient consented to receive emails, &#39;denied&#39; &#x3D; recipient declined to receive emails. (optional)</param>
        /// <param name="engagementStatus">Status of the recipient&#39;s engagement with the emails. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of EmailListResponse</returns>
        public GoodSender.Client.ApiResponse<EmailListResponse> ListEmailConsentsWithHttpInfo(string domain, int? limit = default, string? cursor = default, string? consentStatus = default, string? engagementStatus = default, int operationIndex = 0)
        {
            // verify the required parameter 'domain' is set
            if (domain == null)
            {
                throw new GoodSender.Client.ApiException(400, "Missing required parameter 'domain' when calling EmailsApi->ListEmailConsents");
            }

            GoodSender.Client.RequestOptions localVarRequestOptions = new GoodSender.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = GoodSender.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            var localVarMultipartFormData = localVarContentType == "multipart/form-data";
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = GoodSender.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.QueryParameters.Add(GoodSender.Client.ClientUtils.ParameterToMultiMap("", "domain", domain));
            if (limit != null)
            {
                localVarRequestOptions.QueryParameters.Add(GoodSender.Client.ClientUtils.ParameterToMultiMap("", "limit", limit));
            }
            if (cursor != null)
            {
                localVarRequestOptions.QueryParameters.Add(GoodSender.Client.ClientUtils.ParameterToMultiMap("", "cursor", cursor));
            }
            if (consentStatus != null)
            {
                localVarRequestOptions.QueryParameters.Add(GoodSender.Client.ClientUtils.ParameterToMultiMap("", "consentStatus", consentStatus));
            }
            if (engagementStatus != null)
            {
                localVarRequestOptions.QueryParameters.Add(GoodSender.Client.ClientUtils.ParameterToMultiMap("", "engagementStatus", engagementStatus));
            }

            localVarRequestOptions.Operation = "EmailsApi.ListEmailConsents";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (bearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<EmailListResponse>("/v1/emails", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ListEmailConsents", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// List email consent statuses Retrieve a paginated list of email consent statuses for a domain.
        /// </summary>
        /// <exception cref="GoodSender.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="domain">Sender domain to filter consent records by.</param>
        /// <param name="limit">Maximum number of records to return. (optional, default to 50)</param>
        /// <param name="cursor">Cursor for pagination. (optional)</param>
        /// <param name="consentStatus">Status of the recipient&#39;s consent for receiving emails. &#39;pending&#39; &#x3D; awaiting consent email send, &#39;requested&#39; &#x3D; consent email dispatched, &#39;failed&#39; &#x3D; consent email delivery failed, &#39;granted&#39; &#x3D; recipient consented to receive emails, &#39;denied&#39; &#x3D; recipient declined to receive emails. (optional)</param>
        /// <param name="engagementStatus">Status of the recipient&#39;s engagement with the emails. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of EmailListResponse</returns>
        public async System.Threading.Tasks.Task<EmailListResponse> ListEmailConsentsAsync(string domain, int? limit = default, string? cursor = default, string? consentStatus = default, string? engagementStatus = default, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default)
        {
            GoodSender.Client.ApiResponse<EmailListResponse> localVarResponse = await ListEmailConsentsWithHttpInfoAsync(domain, limit, cursor, consentStatus, engagementStatus, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// List email consent statuses Retrieve a paginated list of email consent statuses for a domain.
        /// </summary>
        /// <exception cref="GoodSender.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="domain">Sender domain to filter consent records by.</param>
        /// <param name="limit">Maximum number of records to return. (optional, default to 50)</param>
        /// <param name="cursor">Cursor for pagination. (optional)</param>
        /// <param name="consentStatus">Status of the recipient&#39;s consent for receiving emails. &#39;pending&#39; &#x3D; awaiting consent email send, &#39;requested&#39; &#x3D; consent email dispatched, &#39;failed&#39; &#x3D; consent email delivery failed, &#39;granted&#39; &#x3D; recipient consented to receive emails, &#39;denied&#39; &#x3D; recipient declined to receive emails. (optional)</param>
        /// <param name="engagementStatus">Status of the recipient&#39;s engagement with the emails. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (EmailListResponse)</returns>
        public async System.Threading.Tasks.Task<GoodSender.Client.ApiResponse<EmailListResponse>> ListEmailConsentsWithHttpInfoAsync(string domain, int? limit = default, string? cursor = default, string? consentStatus = default, string? engagementStatus = default, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default)
        {
            // verify the required parameter 'domain' is set
            if (domain == null)
            {
                throw new GoodSender.Client.ApiException(400, "Missing required parameter 'domain' when calling EmailsApi->ListEmailConsents");
            }


            GoodSender.Client.RequestOptions localVarRequestOptions = new GoodSender.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = GoodSender.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = GoodSender.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.QueryParameters.Add(GoodSender.Client.ClientUtils.ParameterToMultiMap("", "domain", domain));
            if (limit != null)
            {
                localVarRequestOptions.QueryParameters.Add(GoodSender.Client.ClientUtils.ParameterToMultiMap("", "limit", limit));
            }
            if (cursor != null)
            {
                localVarRequestOptions.QueryParameters.Add(GoodSender.Client.ClientUtils.ParameterToMultiMap("", "cursor", cursor));
            }
            if (consentStatus != null)
            {
                localVarRequestOptions.QueryParameters.Add(GoodSender.Client.ClientUtils.ParameterToMultiMap("", "consentStatus", consentStatus));
            }
            if (engagementStatus != null)
            {
                localVarRequestOptions.QueryParameters.Add(GoodSender.Client.ClientUtils.ParameterToMultiMap("", "engagementStatus", engagementStatus));
            }

            localVarRequestOptions.Operation = "EmailsApi.ListEmailConsents";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (bearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<EmailListResponse>("/v1/emails", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ListEmailConsents", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Request recipients&#39; consent to receive emails from your domain Send a consent message to each address so recipients can approve or reject future emails from your domain. Include the email addresses in the request body to start the consent flow. 
        /// </summary>
        /// <exception cref="GoodSender.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="consentEmailRequest"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ConsentEmailResult</returns>
        public ConsentEmailResult RequestEmailConsent(ConsentEmailRequest consentEmailRequest, int operationIndex = 0)
        {
            GoodSender.Client.ApiResponse<ConsentEmailResult> localVarResponse = RequestEmailConsentWithHttpInfo(consentEmailRequest);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Request recipients&#39; consent to receive emails from your domain Send a consent message to each address so recipients can approve or reject future emails from your domain. Include the email addresses in the request body to start the consent flow. 
        /// </summary>
        /// <exception cref="GoodSender.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="consentEmailRequest"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of ConsentEmailResult</returns>
        public GoodSender.Client.ApiResponse<ConsentEmailResult> RequestEmailConsentWithHttpInfo(ConsentEmailRequest consentEmailRequest, int operationIndex = 0)
        {
            // verify the required parameter 'consentEmailRequest' is set
            if (consentEmailRequest == null)
            {
                throw new GoodSender.Client.ApiException(400, "Missing required parameter 'consentEmailRequest' when calling EmailsApi->RequestEmailConsent");
            }

            GoodSender.Client.RequestOptions localVarRequestOptions = new GoodSender.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = GoodSender.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            var localVarMultipartFormData = localVarContentType == "multipart/form-data";
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = GoodSender.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = consentEmailRequest;

            localVarRequestOptions.Operation = "EmailsApi.RequestEmailConsent";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (bearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<ConsentEmailResult>("/v1/emails/consent", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("RequestEmailConsent", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Request recipients&#39; consent to receive emails from your domain Send a consent message to each address so recipients can approve or reject future emails from your domain. Include the email addresses in the request body to start the consent flow. 
        /// </summary>
        /// <exception cref="GoodSender.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="consentEmailRequest"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ConsentEmailResult</returns>
        public async System.Threading.Tasks.Task<ConsentEmailResult> RequestEmailConsentAsync(ConsentEmailRequest consentEmailRequest, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default)
        {
            GoodSender.Client.ApiResponse<ConsentEmailResult> localVarResponse = await RequestEmailConsentWithHttpInfoAsync(consentEmailRequest, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Request recipients&#39; consent to receive emails from your domain Send a consent message to each address so recipients can approve or reject future emails from your domain. Include the email addresses in the request body to start the consent flow. 
        /// </summary>
        /// <exception cref="GoodSender.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="consentEmailRequest"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ConsentEmailResult)</returns>
        public async System.Threading.Tasks.Task<GoodSender.Client.ApiResponse<ConsentEmailResult>> RequestEmailConsentWithHttpInfoAsync(ConsentEmailRequest consentEmailRequest, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default)
        {
            // verify the required parameter 'consentEmailRequest' is set
            if (consentEmailRequest == null)
            {
                throw new GoodSender.Client.ApiException(400, "Missing required parameter 'consentEmailRequest' when calling EmailsApi->RequestEmailConsent");
            }


            GoodSender.Client.RequestOptions localVarRequestOptions = new GoodSender.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = GoodSender.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = GoodSender.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = consentEmailRequest;

            localVarRequestOptions.Operation = "EmailsApi.RequestEmailConsent";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (bearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<ConsentEmailResult>("/v1/emails/consent", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("RequestEmailConsent", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Send an email or a batch of emails Send one or more emails. Emails can be sent only to recipients who have opted in to receive communications from your domain. The response indicates how many emails were sent versus not sent, based on each recipient&#39;s consent state. 
        /// </summary>
        /// <exception cref="GoodSender.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="sendEmailRequest">List of emails to send</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>SendEmailResponse</returns>
        public SendEmailResponse SendEmail(SendEmailRequest sendEmailRequest, int operationIndex = 0)
        {
            GoodSender.Client.ApiResponse<SendEmailResponse> localVarResponse = SendEmailWithHttpInfo(sendEmailRequest);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Send an email or a batch of emails Send one or more emails. Emails can be sent only to recipients who have opted in to receive communications from your domain. The response indicates how many emails were sent versus not sent, based on each recipient&#39;s consent state. 
        /// </summary>
        /// <exception cref="GoodSender.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="sendEmailRequest">List of emails to send</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of SendEmailResponse</returns>
        public GoodSender.Client.ApiResponse<SendEmailResponse> SendEmailWithHttpInfo(SendEmailRequest sendEmailRequest, int operationIndex = 0)
        {
            // verify the required parameter 'sendEmailRequest' is set
            if (sendEmailRequest == null)
            {
                throw new GoodSender.Client.ApiException(400, "Missing required parameter 'sendEmailRequest' when calling EmailsApi->SendEmail");
            }

            GoodSender.Client.RequestOptions localVarRequestOptions = new GoodSender.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = GoodSender.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            var localVarMultipartFormData = localVarContentType == "multipart/form-data";
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = GoodSender.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = sendEmailRequest;

            localVarRequestOptions.Operation = "EmailsApi.SendEmail";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (bearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<SendEmailResponse>("/v1/emails/send", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("SendEmail", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Send an email or a batch of emails Send one or more emails. Emails can be sent only to recipients who have opted in to receive communications from your domain. The response indicates how many emails were sent versus not sent, based on each recipient&#39;s consent state. 
        /// </summary>
        /// <exception cref="GoodSender.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="sendEmailRequest">List of emails to send</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of SendEmailResponse</returns>
        public async System.Threading.Tasks.Task<SendEmailResponse> SendEmailAsync(SendEmailRequest sendEmailRequest, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default)
        {
            GoodSender.Client.ApiResponse<SendEmailResponse> localVarResponse = await SendEmailWithHttpInfoAsync(sendEmailRequest, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Send an email or a batch of emails Send one or more emails. Emails can be sent only to recipients who have opted in to receive communications from your domain. The response indicates how many emails were sent versus not sent, based on each recipient&#39;s consent state. 
        /// </summary>
        /// <exception cref="GoodSender.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="sendEmailRequest">List of emails to send</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (SendEmailResponse)</returns>
        public async System.Threading.Tasks.Task<GoodSender.Client.ApiResponse<SendEmailResponse>> SendEmailWithHttpInfoAsync(SendEmailRequest sendEmailRequest, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default)
        {
            // verify the required parameter 'sendEmailRequest' is set
            if (sendEmailRequest == null)
            {
                throw new GoodSender.Client.ApiException(400, "Missing required parameter 'sendEmailRequest' when calling EmailsApi->SendEmail");
            }


            GoodSender.Client.RequestOptions localVarRequestOptions = new GoodSender.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = GoodSender.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = GoodSender.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = sendEmailRequest;

            localVarRequestOptions.Operation = "EmailsApi.SendEmail";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (bearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<SendEmailResponse>("/v1/emails/send", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("SendEmail", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Send a transactional email using a template Send a transactional email using a predefined template for common use cases like OTP codes, order confirmations, and new device login alerts. If the recipient has \&quot;denied\&quot; consent, the response returns &#x60;{\&quot;status\&quot;: \&quot;declined\&quot;}&#x60; and the email is not sent. Unknown recipients are auto-registered with \&quot;pending\&quot; consent. The template endpoint does not change the recipient&#39;s consent. Each email includes an approve/reject footer allowing the recipient to manage future communications. Provide the template ID and any variables to fill in the placeholders. All variables are optional and will be replaced with an empty string if omitted. URL-type variables must point to the same domain as the sender&#39;s email address. 
        /// </summary>
        /// <exception cref="GoodSender.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="templateEmailRequest">Template email to send</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>TemplateEmailResponse</returns>
        public TemplateEmailResponse SendTemplateEmail(TemplateEmailRequest templateEmailRequest, int operationIndex = 0)
        {
            GoodSender.Client.ApiResponse<TemplateEmailResponse> localVarResponse = SendTemplateEmailWithHttpInfo(templateEmailRequest);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Send a transactional email using a template Send a transactional email using a predefined template for common use cases like OTP codes, order confirmations, and new device login alerts. If the recipient has \&quot;denied\&quot; consent, the response returns &#x60;{\&quot;status\&quot;: \&quot;declined\&quot;}&#x60; and the email is not sent. Unknown recipients are auto-registered with \&quot;pending\&quot; consent. The template endpoint does not change the recipient&#39;s consent. Each email includes an approve/reject footer allowing the recipient to manage future communications. Provide the template ID and any variables to fill in the placeholders. All variables are optional and will be replaced with an empty string if omitted. URL-type variables must point to the same domain as the sender&#39;s email address. 
        /// </summary>
        /// <exception cref="GoodSender.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="templateEmailRequest">Template email to send</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of TemplateEmailResponse</returns>
        public GoodSender.Client.ApiResponse<TemplateEmailResponse> SendTemplateEmailWithHttpInfo(TemplateEmailRequest templateEmailRequest, int operationIndex = 0)
        {
            // verify the required parameter 'templateEmailRequest' is set
            if (templateEmailRequest == null)
            {
                throw new GoodSender.Client.ApiException(400, "Missing required parameter 'templateEmailRequest' when calling EmailsApi->SendTemplateEmail");
            }

            GoodSender.Client.RequestOptions localVarRequestOptions = new GoodSender.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = GoodSender.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            var localVarMultipartFormData = localVarContentType == "multipart/form-data";
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = GoodSender.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = templateEmailRequest;

            localVarRequestOptions.Operation = "EmailsApi.SendTemplateEmail";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (bearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<TemplateEmailResponse>("/v1/emails/template", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("SendTemplateEmail", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Send a transactional email using a template Send a transactional email using a predefined template for common use cases like OTP codes, order confirmations, and new device login alerts. If the recipient has \&quot;denied\&quot; consent, the response returns &#x60;{\&quot;status\&quot;: \&quot;declined\&quot;}&#x60; and the email is not sent. Unknown recipients are auto-registered with \&quot;pending\&quot; consent. The template endpoint does not change the recipient&#39;s consent. Each email includes an approve/reject footer allowing the recipient to manage future communications. Provide the template ID and any variables to fill in the placeholders. All variables are optional and will be replaced with an empty string if omitted. URL-type variables must point to the same domain as the sender&#39;s email address. 
        /// </summary>
        /// <exception cref="GoodSender.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="templateEmailRequest">Template email to send</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of TemplateEmailResponse</returns>
        public async System.Threading.Tasks.Task<TemplateEmailResponse> SendTemplateEmailAsync(TemplateEmailRequest templateEmailRequest, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default)
        {
            GoodSender.Client.ApiResponse<TemplateEmailResponse> localVarResponse = await SendTemplateEmailWithHttpInfoAsync(templateEmailRequest, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Send a transactional email using a template Send a transactional email using a predefined template for common use cases like OTP codes, order confirmations, and new device login alerts. If the recipient has \&quot;denied\&quot; consent, the response returns &#x60;{\&quot;status\&quot;: \&quot;declined\&quot;}&#x60; and the email is not sent. Unknown recipients are auto-registered with \&quot;pending\&quot; consent. The template endpoint does not change the recipient&#39;s consent. Each email includes an approve/reject footer allowing the recipient to manage future communications. Provide the template ID and any variables to fill in the placeholders. All variables are optional and will be replaced with an empty string if omitted. URL-type variables must point to the same domain as the sender&#39;s email address. 
        /// </summary>
        /// <exception cref="GoodSender.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="templateEmailRequest">Template email to send</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (TemplateEmailResponse)</returns>
        public async System.Threading.Tasks.Task<GoodSender.Client.ApiResponse<TemplateEmailResponse>> SendTemplateEmailWithHttpInfoAsync(TemplateEmailRequest templateEmailRequest, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default)
        {
            // verify the required parameter 'templateEmailRequest' is set
            if (templateEmailRequest == null)
            {
                throw new GoodSender.Client.ApiException(400, "Missing required parameter 'templateEmailRequest' when calling EmailsApi->SendTemplateEmail");
            }


            GoodSender.Client.RequestOptions localVarRequestOptions = new GoodSender.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = GoodSender.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = GoodSender.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = templateEmailRequest;

            localVarRequestOptions.Operation = "EmailsApi.SendTemplateEmail";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (bearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<TemplateEmailResponse>("/v1/emails/template", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("SendTemplateEmail", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

    }
}
