/*
 * Goodsender API
 *
 * Goodsender API. ### Authorization  All API requests require an API key in the `Authorization` header:  ``` Authorization: Bearer <your-api-key> ``` 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@goodsender.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GoodSender.Model;
using GoodSender.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace GoodSender.Test.Model
{
    /// <summary>
    ///  Class for testing Attachment
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AttachmentTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Attachment
        //private Attachment instance;

        public AttachmentTests()
        {
            // TODO uncomment below to create an instance of Attachment
            //instance = new Attachment();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Attachment
        /// </summary>
        [Fact]
        public void AttachmentInstanceTest()
        {
            // TODO uncomment below to test "IsType" Attachment
            //Assert.IsType<Attachment>(instance);
        }

        /// <summary>
        /// Test the property 'FileName'
        /// </summary>
        [Fact]
        public void FileNameTest()
        {
            // TODO unit test for the property 'FileName'
        }

        /// <summary>
        /// Test the property 'Content'
        /// </summary>
        [Fact]
        public void ContentTest()
        {
            // TODO unit test for the property 'Content'
        }

        /// <summary>
        /// Test the property 'ContentType'
        /// </summary>
        [Fact]
        public void ContentTypeTest()
        {
            // TODO unit test for the property 'ContentType'
        }

        /// <summary>
        /// Test the property 'InlineId'
        /// </summary>
        [Fact]
        public void InlineIdTest()
        {
            // TODO unit test for the property 'InlineId'
        }
    }
}
