/*
 * Goodsender API
 *
 * Goodsender API. ### Authorization  All API requests require an API key in the `Authorization` header:  ``` Authorization: Bearer <your-api-key> ``` 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@goodsender.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GoodSender.Model;
using GoodSender.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace GoodSender.Test.Model
{
    /// <summary>
    ///  Class for testing ConsentEmailEntry
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ConsentEmailEntryTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ConsentEmailEntry
        //private ConsentEmailEntry instance;

        public ConsentEmailEntryTests()
        {
            // TODO uncomment below to create an instance of ConsentEmailEntry
            //instance = new ConsentEmailEntry();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ConsentEmailEntry
        /// </summary>
        [Fact]
        public void ConsentEmailEntryInstanceTest()
        {
            // TODO uncomment below to test "IsType" ConsentEmailEntry
            //Assert.IsType<ConsentEmailEntry>(instance);
        }

        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Fact]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
    }
}
