/*
 * Goodsender API
 *
 * Goodsender API. ### Authorization  All API requests require an API key in the `Authorization` header:  ``` Authorization: Bearer <your-api-key> ``` 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@goodsender.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GoodSender.Model;
using GoodSender.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace GoodSender.Test.Model
{
    /// <summary>
    ///  Class for testing DomainVerification
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DomainVerificationTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DomainVerification
        //private DomainVerification instance;

        public DomainVerificationTests()
        {
            // TODO uncomment below to create an instance of DomainVerification
            //instance = new DomainVerification();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DomainVerification
        /// </summary>
        [Fact]
        public void DomainVerificationInstanceTest()
        {
            // TODO uncomment below to test "IsType" DomainVerification
            //Assert.IsType<DomainVerification>(instance);
        }

        /// <summary>
        /// Test the property 'Verified'
        /// </summary>
        [Fact]
        public void VerifiedTest()
        {
            // TODO unit test for the property 'Verified'
        }

        /// <summary>
        /// Test the property 'TrackingVerified'
        /// </summary>
        [Fact]
        public void TrackingVerifiedTest()
        {
            // TODO unit test for the property 'TrackingVerified'
        }

        /// <summary>
        /// Test the property 'ReturnPathVerified'
        /// </summary>
        [Fact]
        public void ReturnPathVerifiedTest()
        {
            // TODO unit test for the property 'ReturnPathVerified'
        }

        /// <summary>
        /// Test the property 'Dkim1Verified'
        /// </summary>
        [Fact]
        public void Dkim1VerifiedTest()
        {
            // TODO unit test for the property 'Dkim1Verified'
        }

        /// <summary>
        /// Test the property 'Dkim2Verified'
        /// </summary>
        [Fact]
        public void Dkim2VerifiedTest()
        {
            // TODO unit test for the property 'Dkim2Verified'
        }
    }
}
