/*
 * Goodsender API
 *
 * Goodsender API. ### Authorization  All API requests require an API key in the `Authorization` header:  ``` Authorization: Bearer <your-api-key> ``` 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@goodsender.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GoodSender.Model;
using GoodSender.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace GoodSender.Test.Model
{
    /// <summary>
    ///  Class for testing Domain
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DomainTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Domain
        //private Domain instance;

        public DomainTests()
        {
            // TODO uncomment below to create an instance of Domain
            //instance = new Domain();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Domain
        /// </summary>
        [Fact]
        public void DomainInstanceTest()
        {
            // TODO uncomment below to test "IsType" Domain
            //Assert.IsType<Domain>(instance);
        }

        /// <summary>
        /// Test the property 'VarDomain'
        /// </summary>
        [Fact]
        public void VarDomainTest()
        {
            // TODO unit test for the property 'VarDomain'
        }

        /// <summary>
        /// Test the property 'Tracking'
        /// </summary>
        [Fact]
        public void TrackingTest()
        {
            // TODO unit test for the property 'Tracking'
        }

        /// <summary>
        /// Test the property 'ReturnPath'
        /// </summary>
        [Fact]
        public void ReturnPathTest()
        {
            // TODO unit test for the property 'ReturnPath'
        }

        /// <summary>
        /// Test the property 'RequireTls'
        /// </summary>
        [Fact]
        public void RequireTlsTest()
        {
            // TODO unit test for the property 'RequireTls'
        }

        /// <summary>
        /// Test the property 'Verification'
        /// </summary>
        [Fact]
        public void VerificationTest()
        {
            // TODO unit test for the property 'Verification'
        }
    }
}
