/*
 * Goodsender API
 *
 * Goodsender API. ### Authorization  All API requests require an API key in the `Authorization` header:  ``` Authorization: Bearer <your-api-key> ``` 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@goodsender.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GoodSender.Model;
using GoodSender.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace GoodSender.Test.Model
{
    /// <summary>
    ///  Class for testing EmailListResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EmailListResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EmailListResponse
        //private EmailListResponse instance;

        public EmailListResponseTests()
        {
            // TODO uncomment below to create an instance of EmailListResponse
            //instance = new EmailListResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EmailListResponse
        /// </summary>
        [Fact]
        public void EmailListResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" EmailListResponse
            //Assert.IsType<EmailListResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Emails'
        /// </summary>
        [Fact]
        public void EmailsTest()
        {
            // TODO unit test for the property 'Emails'
        }

        /// <summary>
        /// Test the property 'NextCursor'
        /// </summary>
        [Fact]
        public void NextCursorTest()
        {
            // TODO unit test for the property 'NextCursor'
        }
    }
}
