/*
 * Goodsender API
 *
 * Goodsender API. ### Authorization  All API requests require an API key in the `Authorization` header:  ``` Authorization: Bearer <your-api-key> ``` 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@goodsender.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GoodSender.Model;
using GoodSender.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace GoodSender.Test.Model
{
    /// <summary>
    ///  Class for testing EmailAccount
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EmailAccountTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EmailAccount
        //private EmailAccount instance;

        public EmailAccountTests()
        {
            // TODO uncomment below to create an instance of EmailAccount
            //instance = new EmailAccount();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EmailAccount
        /// </summary>
        [Fact]
        public void EmailAccountInstanceTest()
        {
            // TODO uncomment below to test "IsType" EmailAccount
            //Assert.IsType<EmailAccount>(instance);
        }

        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Fact]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Domain'
        /// </summary>
        [Fact]
        public void DomainTest()
        {
            // TODO unit test for the property 'Domain'
        }

        /// <summary>
        /// Test the property 'ConsentStatus'
        /// </summary>
        [Fact]
        public void ConsentStatusTest()
        {
            // TODO unit test for the property 'ConsentStatus'
        }

        /// <summary>
        /// Test the property 'EngagementStatus'
        /// </summary>
        [Fact]
        public void EngagementStatusTest()
        {
            // TODO unit test for the property 'EngagementStatus'
        }
    }
}
