/*
 * Goodsender API
 *
 * Goodsender API. ### Authorization  All API requests require an API key in the `Authorization` header:  ``` Authorization: Bearer <your-api-key> ``` 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@goodsender.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GoodSender.Model;
using GoodSender.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace GoodSender.Test.Model
{
    /// <summary>
    ///  Class for testing QuotaExceededError
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class QuotaExceededErrorTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for QuotaExceededError
        //private QuotaExceededError instance;

        public QuotaExceededErrorTests()
        {
            // TODO uncomment below to create an instance of QuotaExceededError
            //instance = new QuotaExceededError();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of QuotaExceededError
        /// </summary>
        [Fact]
        public void QuotaExceededErrorInstanceTest()
        {
            // TODO uncomment below to test "IsType" QuotaExceededError
            //Assert.IsType<QuotaExceededError>(instance);
        }

        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Fact]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }

        /// <summary>
        /// Test the property 'Kind'
        /// </summary>
        [Fact]
        public void KindTest()
        {
            // TODO unit test for the property 'Kind'
        }

        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Fact]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }

        /// <summary>
        /// Test the property 'Limit'
        /// </summary>
        [Fact]
        public void LimitTest()
        {
            // TODO unit test for the property 'Limit'
        }

        /// <summary>
        /// Test the property 'Used'
        /// </summary>
        [Fact]
        public void UsedTest()
        {
            // TODO unit test for the property 'Used'
        }

        /// <summary>
        /// Test the property 'ResetAt'
        /// </summary>
        [Fact]
        public void ResetAtTest()
        {
            // TODO unit test for the property 'ResetAt'
        }
    }
}
