/*
 * Goodsender API
 *
 * Goodsender API. ### Authorization  All API requests require an API key in the `Authorization` header:  ``` Authorization: Bearer <your-api-key> ``` 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@goodsender.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GoodSender.Model;
using GoodSender.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace GoodSender.Test.Model
{
    /// <summary>
    ///  Class for testing SendEmail
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SendEmailTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SendEmail
        //private SendEmail instance;

        public SendEmailTests()
        {
            // TODO uncomment below to create an instance of SendEmail
            //instance = new SendEmail();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SendEmail
        /// </summary>
        [Fact]
        public void SendEmailInstanceTest()
        {
            // TODO uncomment below to test "IsType" SendEmail
            //Assert.IsType<SendEmail>(instance);
        }

        /// <summary>
        /// Test the property 'From'
        /// </summary>
        [Fact]
        public void FromTest()
        {
            // TODO unit test for the property 'From'
        }

        /// <summary>
        /// Test the property 'To'
        /// </summary>
        [Fact]
        public void ToTest()
        {
            // TODO unit test for the property 'To'
        }

        /// <summary>
        /// Test the property 'Subject'
        /// </summary>
        [Fact]
        public void SubjectTest()
        {
            // TODO unit test for the property 'Subject'
        }

        /// <summary>
        /// Test the property 'TextContent'
        /// </summary>
        [Fact]
        public void TextContentTest()
        {
            // TODO unit test for the property 'TextContent'
        }

        /// <summary>
        /// Test the property 'HtmlContent'
        /// </summary>
        [Fact]
        public void HtmlContentTest()
        {
            // TODO unit test for the property 'HtmlContent'
        }

        /// <summary>
        /// Test the property 'MarkdownContent'
        /// </summary>
        [Fact]
        public void MarkdownContentTest()
        {
            // TODO unit test for the property 'MarkdownContent'
        }

        /// <summary>
        /// Test the property 'TemplateId'
        /// </summary>
        [Fact]
        public void TemplateIdTest()
        {
            // TODO unit test for the property 'TemplateId'
        }

        /// <summary>
        /// Test the property 'TemplateData'
        /// </summary>
        [Fact]
        public void TemplateDataTest()
        {
            // TODO unit test for the property 'TemplateData'
        }

        /// <summary>
        /// Test the property 'Attachments'
        /// </summary>
        [Fact]
        public void AttachmentsTest()
        {
            // TODO unit test for the property 'Attachments'
        }

        /// <summary>
        /// Test the property 'Headers'
        /// </summary>
        [Fact]
        public void HeadersTest()
        {
            // TODO unit test for the property 'Headers'
        }

        /// <summary>
        /// Test the property 'ReplyTo'
        /// </summary>
        [Fact]
        public void ReplyToTest()
        {
            // TODO unit test for the property 'ReplyTo'
        }

        /// <summary>
        /// Test the property 'SendTime'
        /// </summary>
        [Fact]
        public void SendTimeTest()
        {
            // TODO unit test for the property 'SendTime'
        }

        /// <summary>
        /// Test the property 'WebhookData'
        /// </summary>
        [Fact]
        public void WebhookDataTest()
        {
            // TODO unit test for the property 'WebhookData'
        }

        /// <summary>
        /// Test the property 'Tag'
        /// </summary>
        [Fact]
        public void TagTest()
        {
            // TODO unit test for the property 'Tag'
        }

        /// <summary>
        /// Test the property 'Tracking'
        /// </summary>
        [Fact]
        public void TrackingTest()
        {
            // TODO unit test for the property 'Tracking'
        }
    }
}
