/*
 * Goodsender API
 *
 * Goodsender API. ### Authorization  All API requests require an API key in the `Authorization` header:  ``` Authorization: Bearer <your-api-key> ``` 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@goodsender.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GoodSender.Model;
using GoodSender.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace GoodSender.Test.Model
{
    /// <summary>
    ///  Class for testing SendEmailResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SendEmailResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SendEmailResponse
        //private SendEmailResponse instance;

        public SendEmailResponseTests()
        {
            // TODO uncomment below to create an instance of SendEmailResponse
            //instance = new SendEmailResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SendEmailResponse
        /// </summary>
        [Fact]
        public void SendEmailResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" SendEmailResponse
            //Assert.IsType<SendEmailResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Sent'
        /// </summary>
        [Fact]
        public void SentTest()
        {
            // TODO unit test for the property 'Sent'
        }

        /// <summary>
        /// Test the property 'Declined'
        /// </summary>
        [Fact]
        public void DeclinedTest()
        {
            // TODO unit test for the property 'Declined'
        }
    }
}
