/*
 * Goodsender API
 *
 * Goodsender API. ### Authorization  All API requests require an API key in the `Authorization` header:  ``` Authorization: Bearer <your-api-key> ``` 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@goodsender.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GoodSender.Model;
using GoodSender.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace GoodSender.Test.Model
{
    /// <summary>
    ///  Class for testing TemplateEmailResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TemplateEmailResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TemplateEmailResponse
        //private TemplateEmailResponse instance;

        public TemplateEmailResponseTests()
        {
            // TODO uncomment below to create an instance of TemplateEmailResponse
            //instance = new TemplateEmailResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TemplateEmailResponse
        /// </summary>
        [Fact]
        public void TemplateEmailResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" TemplateEmailResponse
            //Assert.IsType<TemplateEmailResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
    }
}
