/*
 * Goodsender API
 *
 * Goodsender API. ### Authorization  All API requests require an API key in the `Authorization` header:  ``` Authorization: Bearer <your-api-key> ``` 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@goodsender.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using GoodSender.Client;
using GoodSender.Api;
// uncomment below to import models
//using GoodSender.Model;

namespace GoodSender.Test.Api
{
    /// <summary>
    ///  Class for testing DomainsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class DomainsApiTests : IDisposable
    {
        private DomainsApi instance;

        public DomainsApiTests()
        {
            instance = new DomainsApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DomainsApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' DomainsApi
            //Assert.IsType<DomainsApi>(instance);
        }

        /// <summary>
        /// Test ListDomains
        /// </summary>
        [Fact]
        public void ListDomainsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? limit = null;
            //string? cursor = null;
            //var response = instance.ListDomains(limit, cursor);
            //Assert.IsType<DomainListResponse>(response);
        }
    }
}
