/*
 * Goodsender API
 *
 * Goodsender API. ### Authorization  All API requests require an API key in the `Authorization` header:  ``` Authorization: Bearer <your-api-key> ``` 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@goodsender.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using GoodSender.Client;
using GoodSender.Api;
// uncomment below to import models
//using GoodSender.Model;

namespace GoodSender.Test.Api
{
    /// <summary>
    ///  Class for testing EmailsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class EmailsApiTests : IDisposable
    {
        private EmailsApi instance;

        public EmailsApiTests()
        {
            instance = new EmailsApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EmailsApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' EmailsApi
            //Assert.IsType<EmailsApi>(instance);
        }

        /// <summary>
        /// Test GetEmailConsentStatus
        /// </summary>
        [Fact]
        public void GetEmailConsentStatusTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string email = null;
            //string? domain = null;
            //var response = instance.GetEmailConsentStatus(email, domain);
            //Assert.IsType<List<EmailAccount>>(response);
        }

        /// <summary>
        /// Test ListEmailConsents
        /// </summary>
        [Fact]
        public void ListEmailConsentsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string domain = null;
            //int? limit = null;
            //string? cursor = null;
            //string? consentStatus = null;
            //string? engagementStatus = null;
            //var response = instance.ListEmailConsents(domain, limit, cursor, consentStatus, engagementStatus);
            //Assert.IsType<EmailListResponse>(response);
        }

        /// <summary>
        /// Test RequestEmailConsent
        /// </summary>
        [Fact]
        public void RequestEmailConsentTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //ConsentEmailRequest consentEmailRequest = null;
            //var response = instance.RequestEmailConsent(consentEmailRequest);
            //Assert.IsType<ConsentEmailResult>(response);
        }

        /// <summary>
        /// Test SendEmail
        /// </summary>
        [Fact]
        public void SendEmailTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //SendEmailRequest sendEmailRequest = null;
            //var response = instance.SendEmail(sendEmailRequest);
            //Assert.IsType<SendEmailResponse>(response);
        }

        /// <summary>
        /// Test SendTemplateEmail
        /// </summary>
        [Fact]
        public void SendTemplateEmailTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //TemplateEmailRequest templateEmailRequest = null;
            //var response = instance.SendTemplateEmail(templateEmailRequest);
            //Assert.IsType<TemplateEmailResponse>(response);
        }
    }
}
