/*
 * Goodsender API
 *
 * Goodsender API. ### Authorization  All API requests require an API key in the `Authorization` header:  ``` Authorization: Bearer <your-api-key> ``` 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@goodsender.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = GoodSender.Client.OpenAPIDateConverter;

namespace GoodSender.Model
{
    /// <summary>
    /// ConsentEmailRequest
    /// </summary>
    [DataContract(Name = "ConsentEmailRequest")]
    public partial class ConsentEmailRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ConsentEmailRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ConsentEmailRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ConsentEmailRequest" /> class.
        /// </summary>
        /// <param name="domain">Domain for the email addresses. (required).</param>
        /// <param name="redirectUrl">URL to which the user will be redirected after providing consent. {email} in the URL will be replaced with the recipient&#39;s email address..</param>
        /// <param name="emails">Recipients to request consent from. Each entry may be either a plain email string or a &#x60;{ email, name? }&#x60; object so callers can attach a display name to a specific recipient. Mixing the two forms in one request is allowed.  (required).</param>
        public ConsentEmailRequest(string domain = default, string redirectUrl = default, List<ConsentEmailEntry> emails = default)
        {
            // to ensure "domain" is required (not null)
            if (domain == null)
            {
                throw new ArgumentNullException("domain is a required property for ConsentEmailRequest and cannot be null");
            }
            this.Domain = domain;
            // to ensure "emails" is required (not null)
            if (emails == null)
            {
                throw new ArgumentNullException("emails is a required property for ConsentEmailRequest and cannot be null");
            }
            this.Emails = emails;
            this.RedirectUrl = redirectUrl;
        }

        /// <summary>
        /// Domain for the email addresses.
        /// </summary>
        /// <value>Domain for the email addresses.</value>
        /*
        <example>example.com</example>
        */
        [DataMember(Name = "domain", IsRequired = true, EmitDefaultValue = true)]
        public string Domain { get; set; }

        /// <summary>
        /// URL to which the user will be redirected after providing consent. {email} in the URL will be replaced with the recipient&#39;s email address.
        /// </summary>
        /// <value>URL to which the user will be redirected after providing consent. {email} in the URL will be replaced with the recipient&#39;s email address.</value>
        /*
        <example>https://example.com/consent/{email}</example>
        */
        [DataMember(Name = "redirect_url", EmitDefaultValue = false)]
        public string RedirectUrl { get; set; }

        /// <summary>
        /// Recipients to request consent from. Each entry may be either a plain email string or a &#x60;{ email, name? }&#x60; object so callers can attach a display name to a specific recipient. Mixing the two forms in one request is allowed. 
        /// </summary>
        /// <value>Recipients to request consent from. Each entry may be either a plain email string or a &#x60;{ email, name? }&#x60; object so callers can attach a display name to a specific recipient. Mixing the two forms in one request is allowed. </value>
        /*
        <example>[user1@example.com, {email&#x3D;user2@example.com, name&#x3D;Jane Doe}]</example>
        */
        [DataMember(Name = "emails", IsRequired = true, EmitDefaultValue = true)]
        public List<ConsentEmailEntry> Emails { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ConsentEmailRequest {\n");
            sb.Append("  Domain: ").Append(Domain).Append("\n");
            sb.Append("  RedirectUrl: ").Append(RedirectUrl).Append("\n");
            sb.Append("  Emails: ").Append(Emails).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
