/*
 * Goodsender API
 *
 * Goodsender API. ### Authorization  All API requests require an API key in the `Authorization` header:  ``` Authorization: Bearer <your-api-key> ``` 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@goodsender.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = GoodSender.Client.OpenAPIDateConverter;

namespace GoodSender.Model
{
    /// <summary>
    /// Per-record verification state for the domain. &#x60;verified&#x60; is the overall flag; the individual &#x60;*_verified&#x60; fields indicate which DNS records still need attention when &#x60;verified&#x60; is &#x60;false&#x60;. 
    /// </summary>
    [DataContract(Name = "DomainVerification")]
    public partial class DomainVerification : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DomainVerification" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected DomainVerification() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="DomainVerification" /> class.
        /// </summary>
        /// <param name="verified">Overall verification status. True only when every required DNS record is in place. (required).</param>
        /// <param name="trackingVerified">Whether the tracking subdomain CNAME is in place. (required).</param>
        /// <param name="returnPathVerified">Whether the return-path subdomain CNAME is in place. (required).</param>
        /// <param name="dkim1Verified">Whether the first DKIM record is in place. (required).</param>
        /// <param name="dkim2Verified">Whether the second DKIM record is in place. (required).</param>
        public DomainVerification(bool verified = default, bool trackingVerified = default, bool returnPathVerified = default, bool dkim1Verified = default, bool dkim2Verified = default)
        {
            this.Verified = verified;
            this.TrackingVerified = trackingVerified;
            this.ReturnPathVerified = returnPathVerified;
            this.Dkim1Verified = dkim1Verified;
            this.Dkim2Verified = dkim2Verified;
        }

        /// <summary>
        /// Overall verification status. True only when every required DNS record is in place.
        /// </summary>
        /// <value>Overall verification status. True only when every required DNS record is in place.</value>
        /*
        <example>true</example>
        */
        [DataMember(Name = "verified", IsRequired = true, EmitDefaultValue = true)]
        public bool Verified { get; set; }

        /// <summary>
        /// Whether the tracking subdomain CNAME is in place.
        /// </summary>
        /// <value>Whether the tracking subdomain CNAME is in place.</value>
        /*
        <example>true</example>
        */
        [DataMember(Name = "tracking_verified", IsRequired = true, EmitDefaultValue = true)]
        public bool TrackingVerified { get; set; }

        /// <summary>
        /// Whether the return-path subdomain CNAME is in place.
        /// </summary>
        /// <value>Whether the return-path subdomain CNAME is in place.</value>
        /*
        <example>true</example>
        */
        [DataMember(Name = "return_path_verified", IsRequired = true, EmitDefaultValue = true)]
        public bool ReturnPathVerified { get; set; }

        /// <summary>
        /// Whether the first DKIM record is in place.
        /// </summary>
        /// <value>Whether the first DKIM record is in place.</value>
        /*
        <example>true</example>
        */
        [DataMember(Name = "dkim1_verified", IsRequired = true, EmitDefaultValue = true)]
        public bool Dkim1Verified { get; set; }

        /// <summary>
        /// Whether the second DKIM record is in place.
        /// </summary>
        /// <value>Whether the second DKIM record is in place.</value>
        /*
        <example>true</example>
        */
        [DataMember(Name = "dkim2_verified", IsRequired = true, EmitDefaultValue = true)]
        public bool Dkim2Verified { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DomainVerification {\n");
            sb.Append("  Verified: ").Append(Verified).Append("\n");
            sb.Append("  TrackingVerified: ").Append(TrackingVerified).Append("\n");
            sb.Append("  ReturnPathVerified: ").Append(ReturnPathVerified).Append("\n");
            sb.Append("  Dkim1Verified: ").Append(Dkim1Verified).Append("\n");
            sb.Append("  Dkim2Verified: ").Append(Dkim2Verified).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
