/*
 * Goodsender API
 *
 * Goodsender API. ### Authorization  All API requests require an API key in the `Authorization` header:  ``` Authorization: Bearer <your-api-key> ``` 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@goodsender.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = GoodSender.Client.OpenAPIDateConverter;

namespace GoodSender.Model
{
    /// <summary>
    /// Domain
    /// </summary>
    [DataContract(Name = "Domain")]
    public partial class Domain : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Domain" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected Domain() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="Domain" /> class.
        /// </summary>
        /// <param name="varDomain">The domain name. (required).</param>
        /// <param name="tracking">Subdomain used for click tracking. (required).</param>
        /// <param name="returnPath">Subdomain used for the return path. (required).</param>
        /// <param name="requireTls">Whether outbound mail from this domain must be sent over TLS. (required).</param>
        /// <param name="verification">verification (required).</param>
        public Domain(string varDomain = default, string tracking = default, string returnPath = default, bool requireTls = default, DomainVerification verification = default)
        {
            // to ensure "varDomain" is required (not null)
            if (varDomain == null)
            {
                throw new ArgumentNullException("varDomain is a required property for Domain and cannot be null");
            }
            this.VarDomain = varDomain;
            // to ensure "tracking" is required (not null)
            if (tracking == null)
            {
                throw new ArgumentNullException("tracking is a required property for Domain and cannot be null");
            }
            this.Tracking = tracking;
            // to ensure "returnPath" is required (not null)
            if (returnPath == null)
            {
                throw new ArgumentNullException("returnPath is a required property for Domain and cannot be null");
            }
            this.ReturnPath = returnPath;
            this.RequireTls = requireTls;
            // to ensure "verification" is required (not null)
            if (verification == null)
            {
                throw new ArgumentNullException("verification is a required property for Domain and cannot be null");
            }
            this.Verification = verification;
        }

        /// <summary>
        /// The domain name.
        /// </summary>
        /// <value>The domain name.</value>
        /*
        <example>example.com</example>
        */
        [DataMember(Name = "domain", IsRequired = true, EmitDefaultValue = true)]
        public string VarDomain { get; set; }

        /// <summary>
        /// Subdomain used for click tracking.
        /// </summary>
        /// <value>Subdomain used for click tracking.</value>
        /*
        <example>track.example.com</example>
        */
        [DataMember(Name = "tracking", IsRequired = true, EmitDefaultValue = true)]
        public string Tracking { get; set; }

        /// <summary>
        /// Subdomain used for the return path.
        /// </summary>
        /// <value>Subdomain used for the return path.</value>
        /*
        <example>bounces.example.com</example>
        */
        [DataMember(Name = "return_path", IsRequired = true, EmitDefaultValue = true)]
        public string ReturnPath { get; set; }

        /// <summary>
        /// Whether outbound mail from this domain must be sent over TLS.
        /// </summary>
        /// <value>Whether outbound mail from this domain must be sent over TLS.</value>
        /*
        <example>true</example>
        */
        [DataMember(Name = "require_tls", IsRequired = true, EmitDefaultValue = true)]
        public bool RequireTls { get; set; }

        /// <summary>
        /// Gets or Sets Verification
        /// </summary>
        [DataMember(Name = "verification", IsRequired = true, EmitDefaultValue = true)]
        public DomainVerification Verification { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Domain {\n");
            sb.Append("  VarDomain: ").Append(VarDomain).Append("\n");
            sb.Append("  Tracking: ").Append(Tracking).Append("\n");
            sb.Append("  ReturnPath: ").Append(ReturnPath).Append("\n");
            sb.Append("  RequireTls: ").Append(RequireTls).Append("\n");
            sb.Append("  Verification: ").Append(Verification).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
