/*
 * Goodsender API
 *
 * Goodsender API. ### Authorization  All API requests require an API key in the `Authorization` header:  ``` Authorization: Bearer <your-api-key> ``` 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@goodsender.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = GoodSender.Client.OpenAPIDateConverter;

namespace GoodSender.Model
{
    /// <summary>
    /// EmailListResponse
    /// </summary>
    [DataContract(Name = "EmailListResponse")]
    public partial class EmailListResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EmailListResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected EmailListResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="EmailListResponse" /> class.
        /// </summary>
        /// <param name="emails">emails (required).</param>
        /// <param name="nextCursor">Cursor to retrieve the next page of results. Omitted if there are no more results..</param>
        public EmailListResponse(List<EmailAccount> emails = default, string nextCursor = default)
        {
            // to ensure "emails" is required (not null)
            if (emails == null)
            {
                throw new ArgumentNullException("emails is a required property for EmailListResponse and cannot be null");
            }
            this.Emails = emails;
            this.NextCursor = nextCursor;
        }

        /// <summary>
        /// Gets or Sets Emails
        /// </summary>
        [DataMember(Name = "emails", IsRequired = true, EmitDefaultValue = true)]
        public List<EmailAccount> Emails { get; set; }

        /// <summary>
        /// Cursor to retrieve the next page of results. Omitted if there are no more results.
        /// </summary>
        /// <value>Cursor to retrieve the next page of results. Omitted if there are no more results.</value>
        /*
        <example>eyJjcmVhdGVkQXRNaWNyb3MiOjE2ODAxMjM0NTY3ODksImVtYWlsIjoidXNlckBleGFtcGxlLmNvbSJ9</example>
        */
        [DataMember(Name = "nextCursor", EmitDefaultValue = false)]
        public string NextCursor { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class EmailListResponse {\n");
            sb.Append("  Emails: ").Append(Emails).Append("\n");
            sb.Append("  NextCursor: ").Append(NextCursor).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
