/*
 * Goodsender API
 *
 * Goodsender API. ### Authorization  All API requests require an API key in the `Authorization` header:  ``` Authorization: Bearer <your-api-key> ``` 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@goodsender.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = GoodSender.Client.OpenAPIDateConverter;

namespace GoodSender.Model
{
    /// <summary>
    /// EmailAccount
    /// </summary>
    [DataContract(Name = "EmailAccount")]
    public partial class EmailAccount : IValidatableObject
    {
        /// <summary>
        /// Status of the recipient&#39;s consent for receiving emails. &#39;pending&#39; &#x3D; awaiting consent email send, &#39;requested&#39; &#x3D; consent email dispatched, &#39;failed&#39; &#x3D; consent email delivery failed, &#39;granted&#39; &#x3D; recipient consented to receive emails, &#39;denied&#39; &#x3D; recipient declined to receive emails.
        /// </summary>
        /// <value>Status of the recipient&#39;s consent for receiving emails. &#39;pending&#39; &#x3D; awaiting consent email send, &#39;requested&#39; &#x3D; consent email dispatched, &#39;failed&#39; &#x3D; consent email delivery failed, &#39;granted&#39; &#x3D; recipient consented to receive emails, &#39;denied&#39; &#x3D; recipient declined to receive emails.</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum ConsentStatusEnum
        {
            /// <summary>
            /// Enum Pending for value: pending
            /// </summary>
            [EnumMember(Value = "pending")]
            Pending = 1,

            /// <summary>
            /// Enum Requested for value: requested
            /// </summary>
            [EnumMember(Value = "requested")]
            Requested = 2,

            /// <summary>
            /// Enum Failed for value: failed
            /// </summary>
            [EnumMember(Value = "failed")]
            Failed = 3,

            /// <summary>
            /// Enum Granted for value: granted
            /// </summary>
            [EnumMember(Value = "granted")]
            Granted = 4,

            /// <summary>
            /// Enum Denied for value: denied
            /// </summary>
            [EnumMember(Value = "denied")]
            Denied = 5
        }


        /// <summary>
        /// Status of the recipient&#39;s consent for receiving emails. &#39;pending&#39; &#x3D; awaiting consent email send, &#39;requested&#39; &#x3D; consent email dispatched, &#39;failed&#39; &#x3D; consent email delivery failed, &#39;granted&#39; &#x3D; recipient consented to receive emails, &#39;denied&#39; &#x3D; recipient declined to receive emails.
        /// </summary>
        /// <value>Status of the recipient&#39;s consent for receiving emails. &#39;pending&#39; &#x3D; awaiting consent email send, &#39;requested&#39; &#x3D; consent email dispatched, &#39;failed&#39; &#x3D; consent email delivery failed, &#39;granted&#39; &#x3D; recipient consented to receive emails, &#39;denied&#39; &#x3D; recipient declined to receive emails.</value>
        /*
        <example>pending</example>
        */
        [DataMember(Name = "consentStatus", IsRequired = true, EmitDefaultValue = true)]
        public ConsentStatusEnum ConsentStatus { get; set; }
        /// <summary>
        /// Status of the recipient&#39;s engagement with the emails.
        /// </summary>
        /// <value>Status of the recipient&#39;s engagement with the emails.</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum EngagementStatusEnum
        {
            /// <summary>
            /// Enum New for value: new
            /// </summary>
            [EnumMember(Value = "new")]
            New = 1,

            /// <summary>
            /// Enum Hot for value: hot
            /// </summary>
            [EnumMember(Value = "hot")]
            Hot = 2,

            /// <summary>
            /// Enum Warm for value: warm
            /// </summary>
            [EnumMember(Value = "warm")]
            Warm = 3,

            /// <summary>
            /// Enum Cooling for value: cooling
            /// </summary>
            [EnumMember(Value = "cooling")]
            Cooling = 4,

            /// <summary>
            /// Enum Dormant for value: dormant
            /// </summary>
            [EnumMember(Value = "dormant")]
            Dormant = 5,

            /// <summary>
            /// Enum Inactive for value: inactive
            /// </summary>
            [EnumMember(Value = "inactive")]
            Inactive = 6
        }


        /// <summary>
        /// Status of the recipient&#39;s engagement with the emails.
        /// </summary>
        /// <value>Status of the recipient&#39;s engagement with the emails.</value>
        /*
        <example>new</example>
        */
        [DataMember(Name = "engagementStatus", EmitDefaultValue = false)]
        public EngagementStatusEnum? EngagementStatus { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="EmailAccount" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected EmailAccount() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="EmailAccount" /> class.
        /// </summary>
        /// <param name="email">Recipient email address. (required).</param>
        /// <param name="name">Optional display name for the recipient. Used in the To header on the consent email when present, and surfaced through the Dashboard. May be null when no name has been provided..</param>
        /// <param name="domain">Domain part of the email address. (required).</param>
        /// <param name="consentStatus">Status of the recipient&#39;s consent for receiving emails. &#39;pending&#39; &#x3D; awaiting consent email send, &#39;requested&#39; &#x3D; consent email dispatched, &#39;failed&#39; &#x3D; consent email delivery failed, &#39;granted&#39; &#x3D; recipient consented to receive emails, &#39;denied&#39; &#x3D; recipient declined to receive emails. (required).</param>
        /// <param name="engagementStatus">Status of the recipient&#39;s engagement with the emails..</param>
        public EmailAccount(string email = default, string name = default, string domain = default, ConsentStatusEnum consentStatus = default, EngagementStatusEnum? engagementStatus = default)
        {
            // to ensure "email" is required (not null)
            if (email == null)
            {
                throw new ArgumentNullException("email is a required property for EmailAccount and cannot be null");
            }
            this.Email = email;
            // to ensure "domain" is required (not null)
            if (domain == null)
            {
                throw new ArgumentNullException("domain is a required property for EmailAccount and cannot be null");
            }
            this.Domain = domain;
            this.ConsentStatus = consentStatus;
            this.Name = name;
            this.EngagementStatus = engagementStatus;
        }

        /// <summary>
        /// Recipient email address.
        /// </summary>
        /// <value>Recipient email address.</value>
        /*
        <example>user@example.com</example>
        */
        [DataMember(Name = "email", IsRequired = true, EmitDefaultValue = true)]
        public string Email { get; set; }

        /// <summary>
        /// Optional display name for the recipient. Used in the To header on the consent email when present, and surfaced through the Dashboard. May be null when no name has been provided.
        /// </summary>
        /// <value>Optional display name for the recipient. Used in the To header on the consent email when present, and surfaced through the Dashboard. May be null when no name has been provided.</value>
        /*
        <example>Jane Doe</example>
        */
        [DataMember(Name = "name", EmitDefaultValue = true)]
        public string Name { get; set; }

        /// <summary>
        /// Domain part of the email address.
        /// </summary>
        /// <value>Domain part of the email address.</value>
        /*
        <example>example.com</example>
        */
        [DataMember(Name = "domain", IsRequired = true, EmitDefaultValue = true)]
        public string Domain { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class EmailAccount {\n");
            sb.Append("  Email: ").Append(Email).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Domain: ").Append(Domain).Append("\n");
            sb.Append("  ConsentStatus: ").Append(ConsentStatus).Append("\n");
            sb.Append("  EngagementStatus: ").Append(EngagementStatus).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
