/*
 * Goodsender API
 *
 * Goodsender API. ### Authorization  All API requests require an API key in the `Authorization` header:  ``` Authorization: Bearer <your-api-key> ``` 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@goodsender.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = GoodSender.Client.OpenAPIDateConverter;

namespace GoodSender.Model
{
    /// <summary>
    /// QuotaExceededError
    /// </summary>
    [DataContract(Name = "QuotaExceededError")]
    public partial class QuotaExceededError : IValidatableObject
    {
        /// <summary>
        /// Machine-readable error code.
        /// </summary>
        /// <value>Machine-readable error code.</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum CodeEnum
        {
            /// <summary>
            /// Enum QuotaExceeded for value: quota_exceeded
            /// </summary>
            [EnumMember(Value = "quota_exceeded")]
            QuotaExceeded = 1
        }


        /// <summary>
        /// Machine-readable error code.
        /// </summary>
        /// <value>Machine-readable error code.</value>
        [DataMember(Name = "code", IsRequired = true, EmitDefaultValue = true)]
        public CodeEnum Code { get; set; }
        /// <summary>
        /// Whether the daily or monthly quota was exhausted.
        /// </summary>
        /// <value>Whether the daily or monthly quota was exhausted.</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum KindEnum
        {
            /// <summary>
            /// Enum Daily for value: daily
            /// </summary>
            [EnumMember(Value = "daily")]
            Daily = 1,

            /// <summary>
            /// Enum Monthly for value: monthly
            /// </summary>
            [EnumMember(Value = "monthly")]
            Monthly = 2
        }


        /// <summary>
        /// Whether the daily or monthly quota was exhausted.
        /// </summary>
        /// <value>Whether the daily or monthly quota was exhausted.</value>
        [DataMember(Name = "kind", IsRequired = true, EmitDefaultValue = true)]
        public KindEnum Kind { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="QuotaExceededError" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected QuotaExceededError() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="QuotaExceededError" /> class.
        /// </summary>
        /// <param name="code">Machine-readable error code. (required).</param>
        /// <param name="kind">Whether the daily or monthly quota was exhausted. (required).</param>
        /// <param name="message">Human-readable error message. (required).</param>
        /// <param name="limit">Quota limit that was reached. (required).</param>
        /// <param name="used">Number of emails already used against the quota. (required).</param>
        /// <param name="resetAt">Timestamp at which the quota window resets. (required).</param>
        public QuotaExceededError(CodeEnum code = default, KindEnum kind = default, string message = default, int limit = default, int used = default, DateTime resetAt = default)
        {
            this.Code = code;
            this.Kind = kind;
            // to ensure "message" is required (not null)
            if (message == null)
            {
                throw new ArgumentNullException("message is a required property for QuotaExceededError and cannot be null");
            }
            this.Message = message;
            this.Limit = limit;
            this.Used = used;
            this.ResetAt = resetAt;
        }

        /// <summary>
        /// Human-readable error message.
        /// </summary>
        /// <value>Human-readable error message.</value>
        [DataMember(Name = "message", IsRequired = true, EmitDefaultValue = true)]
        public string Message { get; set; }

        /// <summary>
        /// Quota limit that was reached.
        /// </summary>
        /// <value>Quota limit that was reached.</value>
        [DataMember(Name = "limit", IsRequired = true, EmitDefaultValue = true)]
        public int Limit { get; set; }

        /// <summary>
        /// Number of emails already used against the quota.
        /// </summary>
        /// <value>Number of emails already used against the quota.</value>
        [DataMember(Name = "used", IsRequired = true, EmitDefaultValue = true)]
        public int Used { get; set; }

        /// <summary>
        /// Timestamp at which the quota window resets.
        /// </summary>
        /// <value>Timestamp at which the quota window resets.</value>
        [DataMember(Name = "resetAt", IsRequired = true, EmitDefaultValue = true)]
        public DateTime ResetAt { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class QuotaExceededError {\n");
            sb.Append("  Code: ").Append(Code).Append("\n");
            sb.Append("  Kind: ").Append(Kind).Append("\n");
            sb.Append("  Message: ").Append(Message).Append("\n");
            sb.Append("  Limit: ").Append(Limit).Append("\n");
            sb.Append("  Used: ").Append(Used).Append("\n");
            sb.Append("  ResetAt: ").Append(ResetAt).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
