/*
 * Goodsender API
 *
 * Goodsender API. ### Authorization  All API requests require an API key in the `Authorization` header:  ``` Authorization: Bearer <your-api-key> ``` 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@goodsender.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = GoodSender.Client.OpenAPIDateConverter;

namespace GoodSender.Model
{
    /// <summary>
    /// SendEmailResponse
    /// </summary>
    [DataContract(Name = "SendEmailResponse")]
    public partial class SendEmailResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SendEmailResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected SendEmailResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="SendEmailResponse" /> class.
        /// </summary>
        /// <param name="sent">Number of emails sent (recipients had consent allowing delivery) (required).</param>
        /// <param name="declined">Number of emails not sent because recipients did not have granted consent to receive emails (required).</param>
        public SendEmailResponse(int sent = default, int declined = default)
        {
            this.Sent = sent;
            this.Declined = declined;
        }

        /// <summary>
        /// Number of emails sent (recipients had consent allowing delivery)
        /// </summary>
        /// <value>Number of emails sent (recipients had consent allowing delivery)</value>
        /*
        <example>8</example>
        */
        [DataMember(Name = "sent", IsRequired = true, EmitDefaultValue = true)]
        public int Sent { get; set; }

        /// <summary>
        /// Number of emails not sent because recipients did not have granted consent to receive emails
        /// </summary>
        /// <value>Number of emails not sent because recipients did not have granted consent to receive emails</value>
        /*
        <example>2</example>
        */
        [DataMember(Name = "declined", IsRequired = true, EmitDefaultValue = true)]
        public int Declined { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SendEmailResponse {\n");
            sb.Append("  Sent: ").Append(Sent).Append("\n");
            sb.Append("  Declined: ").Append(Declined).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
