/*
 * Goodsender API
 *
 * Goodsender API. ### Authorization  All API requests require an API key in the `Authorization` header:  ``` Authorization: Bearer <your-api-key> ``` 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@goodsender.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = GoodSender.Client.OpenAPIDateConverter;

namespace GoodSender.Model
{
    /// <summary>
    /// SendEmailRequest
    /// </summary>
    [DataContract(Name = "SendEmailRequest")]
    public partial class SendEmailRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SendEmailRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected SendEmailRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="SendEmailRequest" /> class.
        /// </summary>
        /// <param name="emails">List of emails to send. Cannot be empty. (required).</param>
        public SendEmailRequest(List<SendEmail> emails = default)
        {
            // to ensure "emails" is required (not null)
            if (emails == null)
            {
                throw new ArgumentNullException("emails is a required property for SendEmailRequest and cannot be null");
            }
            this.Emails = emails;
        }

        /// <summary>
        /// List of emails to send. Cannot be empty.
        /// </summary>
        /// <value>List of emails to send. Cannot be empty.</value>
        [DataMember(Name = "emails", IsRequired = true, EmitDefaultValue = true)]
        public List<SendEmail> Emails { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SendEmailRequest {\n");
            sb.Append("  Emails: ").Append(Emails).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
