/*
 * Goodsender API
 *
 * Goodsender API. ### Authorization  All API requests require an API key in the `Authorization` header:  ``` Authorization: Bearer <your-api-key> ``` 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@goodsender.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = GoodSender.Client.OpenAPIDateConverter;

namespace GoodSender.Model
{
    /// <summary>
    /// Must provide valid sender and subject. At least one recipient (from &#39;to&#39;, &#39;cc&#39;, or &#39;bcc&#39;) is required. Either &#39;text_content&#39;, &#39;html_content&#39;, &#39;markdown_content&#39;, or &#39;template_id&#39; is required. When &#39;markdown_content&#39; is provided, &#39;text_content&#39; and &#39;html_content&#39; are ignored. 
    /// </summary>
    [DataContract(Name = "SendEmail")]
    public partial class SendEmail : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SendEmail" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected SendEmail() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="SendEmail" /> class.
        /// </summary>
        /// <param name="from">Sender address (required) (required).</param>
        /// <param name="to">To recipients. At least one recipient (to, cc, or bcc) is required. Maximum 1000 recipients per email. (required).</param>
        /// <param name="subject">The subject of the email (required) (required) (default to &quot;&quot;).</param>
        /// <param name="textContent">Plain text content.</param>
        /// <param name="htmlContent">HTML content.</param>
        /// <param name="markdownContent">Markdown content. When provided, text_content and html_content are ignored. The raw markdown is used as text_content and rendered to HTML for html_content. .</param>
        /// <param name="templateId">Template ID for templated emails.</param>
        /// <param name="templateData">Data to populate template variables.</param>
        /// <param name="attachments">Email attachments.</param>
        /// <param name="headers">Custom email headers.</param>
        /// <param name="replyTo">Reply-to address.</param>
        /// <param name="sendTime">Unix timestamp for when to send the email. Must not be more than 72 hours in the future. If 0, sends immediately..</param>
        /// <param name="webhookData">Custom data to include in webhook events. Maximum 10 keys, key length 50 chars, value length 100 chars..</param>
        /// <param name="tag">Custom tag for tracking. Maximum 100 characters..</param>
        /// <param name="tracking">Email tracking settings.</param>
        public SendEmail(Address from = default, List<Address> to = default, string subject = @"", string textContent = default, string htmlContent = default, string markdownContent = default, string templateId = default, Dictionary<string, Object> templateData = default, List<Attachment> attachments = default, Dictionary<string, string> headers = default, Address replyTo = default, long sendTime = default, Dictionary<string, string> webhookData = default, string tag = default, TrackingSettings tracking = default)
        {
            // to ensure "from" is required (not null)
            if (from == null)
            {
                throw new ArgumentNullException("from is a required property for SendEmail and cannot be null");
            }
            this.From = from;
            // to ensure "to" is required (not null)
            if (to == null)
            {
                throw new ArgumentNullException("to is a required property for SendEmail and cannot be null");
            }
            this.To = to;
            // to ensure "subject" is required (not null)
            if (subject == null)
            {
                throw new ArgumentNullException("subject is a required property for SendEmail and cannot be null");
            }
            this.Subject = subject;
            this.TextContent = textContent;
            this.HtmlContent = htmlContent;
            this.MarkdownContent = markdownContent;
            this.TemplateId = templateId;
            this.TemplateData = templateData;
            this.Attachments = attachments;
            this.Headers = headers;
            this.ReplyTo = replyTo;
            this.SendTime = sendTime;
            this.WebhookData = webhookData;
            this.Tag = tag;
            this.Tracking = tracking;
        }

        /// <summary>
        /// Sender address (required)
        /// </summary>
        /// <value>Sender address (required)</value>
        [DataMember(Name = "from", IsRequired = true, EmitDefaultValue = true)]
        public Address From { get; set; }

        /// <summary>
        /// To recipients. At least one recipient (to, cc, or bcc) is required. Maximum 1000 recipients per email.
        /// </summary>
        /// <value>To recipients. At least one recipient (to, cc, or bcc) is required. Maximum 1000 recipients per email.</value>
        [DataMember(Name = "to", IsRequired = true, EmitDefaultValue = true)]
        public List<Address> To { get; set; }

        /// <summary>
        /// The subject of the email (required)
        /// </summary>
        /// <value>The subject of the email (required)</value>
        [DataMember(Name = "subject", IsRequired = true, EmitDefaultValue = true)]
        public string Subject { get; set; }

        /// <summary>
        /// Plain text content
        /// </summary>
        /// <value>Plain text content</value>
        [DataMember(Name = "text_content", EmitDefaultValue = false)]
        public string TextContent { get; set; }

        /// <summary>
        /// HTML content
        /// </summary>
        /// <value>HTML content</value>
        [DataMember(Name = "html_content", EmitDefaultValue = false)]
        public string HtmlContent { get; set; }

        /// <summary>
        /// Markdown content. When provided, text_content and html_content are ignored. The raw markdown is used as text_content and rendered to HTML for html_content. 
        /// </summary>
        /// <value>Markdown content. When provided, text_content and html_content are ignored. The raw markdown is used as text_content and rendered to HTML for html_content. </value>
        [DataMember(Name = "markdown_content", EmitDefaultValue = false)]
        public string MarkdownContent { get; set; }

        /// <summary>
        /// Template ID for templated emails
        /// </summary>
        /// <value>Template ID for templated emails</value>
        [DataMember(Name = "template_id", EmitDefaultValue = false)]
        public string TemplateId { get; set; }

        /// <summary>
        /// Data to populate template variables
        /// </summary>
        /// <value>Data to populate template variables</value>
        [DataMember(Name = "template_data", EmitDefaultValue = false)]
        public Dictionary<string, Object> TemplateData { get; set; }

        /// <summary>
        /// Email attachments
        /// </summary>
        /// <value>Email attachments</value>
        [DataMember(Name = "attachments", EmitDefaultValue = false)]
        public List<Attachment> Attachments { get; set; }

        /// <summary>
        /// Custom email headers
        /// </summary>
        /// <value>Custom email headers</value>
        [DataMember(Name = "headers", EmitDefaultValue = false)]
        public Dictionary<string, string> Headers { get; set; }

        /// <summary>
        /// Reply-to address
        /// </summary>
        /// <value>Reply-to address</value>
        [DataMember(Name = "reply_to", EmitDefaultValue = false)]
        public Address ReplyTo { get; set; }

        /// <summary>
        /// Unix timestamp for when to send the email. Must not be more than 72 hours in the future. If 0, sends immediately.
        /// </summary>
        /// <value>Unix timestamp for when to send the email. Must not be more than 72 hours in the future. If 0, sends immediately.</value>
        [DataMember(Name = "send_time", EmitDefaultValue = false)]
        public long SendTime { get; set; }

        /// <summary>
        /// Custom data to include in webhook events. Maximum 10 keys, key length 50 chars, value length 100 chars.
        /// </summary>
        /// <value>Custom data to include in webhook events. Maximum 10 keys, key length 50 chars, value length 100 chars.</value>
        [DataMember(Name = "webhook_data", EmitDefaultValue = false)]
        public Dictionary<string, string> WebhookData { get; set; }

        /// <summary>
        /// Custom tag for tracking. Maximum 100 characters.
        /// </summary>
        /// <value>Custom tag for tracking. Maximum 100 characters.</value>
        [DataMember(Name = "tag", EmitDefaultValue = false)]
        public string Tag { get; set; }

        /// <summary>
        /// Email tracking settings
        /// </summary>
        /// <value>Email tracking settings</value>
        [DataMember(Name = "tracking", EmitDefaultValue = false)]
        public TrackingSettings Tracking { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SendEmail {\n");
            sb.Append("  From: ").Append(From).Append("\n");
            sb.Append("  To: ").Append(To).Append("\n");
            sb.Append("  Subject: ").Append(Subject).Append("\n");
            sb.Append("  TextContent: ").Append(TextContent).Append("\n");
            sb.Append("  HtmlContent: ").Append(HtmlContent).Append("\n");
            sb.Append("  MarkdownContent: ").Append(MarkdownContent).Append("\n");
            sb.Append("  TemplateId: ").Append(TemplateId).Append("\n");
            sb.Append("  TemplateData: ").Append(TemplateData).Append("\n");
            sb.Append("  Attachments: ").Append(Attachments).Append("\n");
            sb.Append("  Headers: ").Append(Headers).Append("\n");
            sb.Append("  ReplyTo: ").Append(ReplyTo).Append("\n");
            sb.Append("  SendTime: ").Append(SendTime).Append("\n");
            sb.Append("  WebhookData: ").Append(WebhookData).Append("\n");
            sb.Append("  Tag: ").Append(Tag).Append("\n");
            sb.Append("  Tracking: ").Append(Tracking).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // MarkdownContent (string) minLength
            if (this.MarkdownContent != null && this.MarkdownContent.Length < 1)
            {
                yield return new ValidationResult("Invalid value for MarkdownContent, length must be greater than 1.", new [] { "MarkdownContent" });
            }

            yield break;
        }
    }

}
