/*
 * Goodsender API
 *
 * Goodsender API. ### Authorization  All API requests require an API key in the `Authorization` header:  ``` Authorization: Bearer <your-api-key> ``` 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@goodsender.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = GoodSender.Client.OpenAPIDateConverter;

namespace GoodSender.Model
{
    /// <summary>
    /// TemplateEmailResponse
    /// </summary>
    [DataContract(Name = "TemplateEmailResponse")]
    public partial class TemplateEmailResponse : IValidatableObject
    {
        /// <summary>
        /// \&quot;sent\&quot; if the email was sent, \&quot;declined\&quot; if the recipient has opted out
        /// </summary>
        /// <value>\&quot;sent\&quot; if the email was sent, \&quot;declined\&quot; if the recipient has opted out</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum StatusEnum
        {
            /// <summary>
            /// Enum Sent for value: sent
            /// </summary>
            [EnumMember(Value = "sent")]
            Sent = 1,

            /// <summary>
            /// Enum Declined for value: declined
            /// </summary>
            [EnumMember(Value = "declined")]
            Declined = 2
        }


        /// <summary>
        /// \&quot;sent\&quot; if the email was sent, \&quot;declined\&quot; if the recipient has opted out
        /// </summary>
        /// <value>\&quot;sent\&quot; if the email was sent, \&quot;declined\&quot; if the recipient has opted out</value>
        /*
        <example>sent</example>
        */
        [DataMember(Name = "status", IsRequired = true, EmitDefaultValue = true)]
        public StatusEnum Status { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="TemplateEmailResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected TemplateEmailResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="TemplateEmailResponse" /> class.
        /// </summary>
        /// <param name="status">\&quot;sent\&quot; if the email was sent, \&quot;declined\&quot; if the recipient has opted out (required).</param>
        public TemplateEmailResponse(StatusEnum status = default)
        {
            this.Status = status;
        }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class TemplateEmailResponse {\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
