/*
 * Goodsender API
 *
 * Goodsender API. ### Authorization  All API requests require an API key in the `Authorization` header:  ``` Authorization: Bearer <your-api-key> ``` 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@goodsender.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = GoodSender.Client.OpenAPIDateConverter;

namespace GoodSender.Model
{
    /// <summary>
    /// TemplateEmailRequestTemplate
    /// </summary>
    [DataContract(Name = "TemplateEmailRequest_template")]
    public partial class TemplateEmailRequestTemplate : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TemplateEmailRequestTemplate" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected TemplateEmailRequestTemplate() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="TemplateEmailRequestTemplate" /> class.
        /// </summary>
        /// <param name="templateId">The ID of the template to use (required).</param>
        /// <param name="variables">Key-value pairs to populate template variables.</param>
        public TemplateEmailRequestTemplate(string templateId = default, Dictionary<string, string> variables = default)
        {
            // to ensure "templateId" is required (not null)
            if (templateId == null)
            {
                throw new ArgumentNullException("templateId is a required property for TemplateEmailRequestTemplate and cannot be null");
            }
            this.TemplateId = templateId;
            this.Variables = variables;
        }

        /// <summary>
        /// The ID of the template to use
        /// </summary>
        /// <value>The ID of the template to use</value>
        [DataMember(Name = "template_id", IsRequired = true, EmitDefaultValue = true)]
        public string TemplateId { get; set; }

        /// <summary>
        /// Key-value pairs to populate template variables
        /// </summary>
        /// <value>Key-value pairs to populate template variables</value>
        [DataMember(Name = "variables", EmitDefaultValue = false)]
        public Dictionary<string, string> Variables { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class TemplateEmailRequestTemplate {\n");
            sb.Append("  TemplateId: ").Append(TemplateId).Append("\n");
            sb.Append("  Variables: ").Append(Variables).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
