/*
 * Goodsender API
 *
 * Goodsender API. ### Authorization  All API requests require an API key in the `Authorization` header:  ``` Authorization: Bearer <your-api-key> ``` 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@goodsender.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = GoodSender.Client.OpenAPIDateConverter;

namespace GoodSender.Model
{
    /// <summary>
    /// TemplateEmailRequest
    /// </summary>
    [DataContract(Name = "TemplateEmailRequest")]
    public partial class TemplateEmailRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TemplateEmailRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected TemplateEmailRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="TemplateEmailRequest" /> class.
        /// </summary>
        /// <param name="from">Sender address (required) (required).</param>
        /// <param name="to">Recipient address (required) (required).</param>
        /// <param name="subject">The subject of the email (required) (required).</param>
        /// <param name="template">template (required).</param>
        public TemplateEmailRequest(Address from = default, Address to = default, string subject = default, TemplateEmailRequestTemplate template = default)
        {
            // to ensure "from" is required (not null)
            if (from == null)
            {
                throw new ArgumentNullException("from is a required property for TemplateEmailRequest and cannot be null");
            }
            this.From = from;
            // to ensure "to" is required (not null)
            if (to == null)
            {
                throw new ArgumentNullException("to is a required property for TemplateEmailRequest and cannot be null");
            }
            this.To = to;
            // to ensure "subject" is required (not null)
            if (subject == null)
            {
                throw new ArgumentNullException("subject is a required property for TemplateEmailRequest and cannot be null");
            }
            this.Subject = subject;
            // to ensure "template" is required (not null)
            if (template == null)
            {
                throw new ArgumentNullException("template is a required property for TemplateEmailRequest and cannot be null");
            }
            this.Template = template;
        }

        /// <summary>
        /// Sender address (required)
        /// </summary>
        /// <value>Sender address (required)</value>
        [DataMember(Name = "from", IsRequired = true, EmitDefaultValue = true)]
        public Address From { get; set; }

        /// <summary>
        /// Recipient address (required)
        /// </summary>
        /// <value>Recipient address (required)</value>
        [DataMember(Name = "to", IsRequired = true, EmitDefaultValue = true)]
        public Address To { get; set; }

        /// <summary>
        /// The subject of the email (required)
        /// </summary>
        /// <value>The subject of the email (required)</value>
        [DataMember(Name = "subject", IsRequired = true, EmitDefaultValue = true)]
        public string Subject { get; set; }

        /// <summary>
        /// Gets or Sets Template
        /// </summary>
        [DataMember(Name = "template", IsRequired = true, EmitDefaultValue = true)]
        public TemplateEmailRequestTemplate Template { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class TemplateEmailRequest {\n");
            sb.Append("  From: ").Append(From).Append("\n");
            sb.Append("  To: ").Append(To).Append("\n");
            sb.Append("  Subject: ").Append(Subject).Append("\n");
            sb.Append("  Template: ").Append(Template).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Subject (string) minLength
            if (this.Subject != null && this.Subject.Length < 1)
            {
                yield return new ValidationResult("Invalid value for Subject, length must be greater than 1.", new [] { "Subject" });
            }

            yield break;
        }
    }

}
