/*
 * Goodsender API
 *
 * Goodsender API. ### Authorization  All API requests require an API key in the `Authorization` header:  ``` Authorization: Bearer <your-api-key> ``` 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@goodsender.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = GoodSender.Client.OpenAPIDateConverter;

namespace GoodSender.Model
{
    /// <summary>
    /// Controls email tracking and unsubscribe settings
    /// </summary>
    [DataContract(Name = "TrackingSettings")]
    public partial class TrackingSettings : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TrackingSettings" /> class.
        /// </summary>
        /// <param name="opens">Whether to track email opens.</param>
        /// <param name="clicks">Whether to track link clicks.</param>
        /// <param name="unsubscribes">Whether to track unsubscribes.</param>
        /// <param name="unsubscribeGroupId">Optional unsubscribe group ID. If not specified, uses global unsubscribe list. This setting is ignored if unsubscribes is false..</param>
        public TrackingSettings(bool opens = default, bool clicks = default, bool unsubscribes = default, long? unsubscribeGroupId = default)
        {
            this.Opens = opens;
            this.Clicks = clicks;
            this.Unsubscribes = unsubscribes;
            this.UnsubscribeGroupId = unsubscribeGroupId;
        }

        /// <summary>
        /// Whether to track email opens
        /// </summary>
        /// <value>Whether to track email opens</value>
        [DataMember(Name = "opens", EmitDefaultValue = true)]
        public bool Opens { get; set; }

        /// <summary>
        /// Whether to track link clicks
        /// </summary>
        /// <value>Whether to track link clicks</value>
        [DataMember(Name = "clicks", EmitDefaultValue = true)]
        public bool Clicks { get; set; }

        /// <summary>
        /// Whether to track unsubscribes
        /// </summary>
        /// <value>Whether to track unsubscribes</value>
        [DataMember(Name = "unsubscribes", EmitDefaultValue = true)]
        public bool Unsubscribes { get; set; }

        /// <summary>
        /// Optional unsubscribe group ID. If not specified, uses global unsubscribe list. This setting is ignored if unsubscribes is false.
        /// </summary>
        /// <value>Optional unsubscribe group ID. If not specified, uses global unsubscribe list. This setting is ignored if unsubscribes is false.</value>
        [DataMember(Name = "unsubscribe_group_id", EmitDefaultValue = true)]
        public long? UnsubscribeGroupId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class TrackingSettings {\n");
            sb.Append("  Opens: ").Append(Opens).Append("\n");
            sb.Append("  Clicks: ").Append(Clicks).Append("\n");
            sb.Append("  Unsubscribes: ").Append(Unsubscribes).Append("\n");
            sb.Append("  UnsubscribeGroupId: ").Append(UnsubscribeGroupId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
